### ISSUE TITLE
TNB Exchange

### ISSUE THREAD

**Issue by Kycermann** [thenewboston-developers/Project-Proposals#104]
#### How would you describe your project?
An exchange made specifically to trade TNB for other crypto currencies and real money a bit later on. No accounts or registration, just simple trading!

I'm in the process of applying for a grant of up to £10,000- some of which we will use for registrations and licences to automatically swap legal tender.

#### What problem does it solve?
Varied/inconsistent exchange rates, potentially unsafe manual trading.

#### Who is the target market?
Buyers and sellers of TNB coins.

#### What do you think is the opportunity of this project?
Stabilise the exchange rate, provide a safe, simple, easy and reliable platform to aquire or sell TNB.

#### How does it integrate with thenewboston digital currency work?
This exchange is specifically made for TNB.

We will provide an API to convert TNB coins into other currencies that various stakeholders are more interested in. For instance, restaurant owners accepting TNB may be more interested in holding USD.

We will create a global market for TNB coins. Investors will have 24/7 access to a fair exchange rate and developers will have the option of swapping some of their coins for legal tender.

#### Are there any competitors?
Nope. This helps everyone :-)

#### Will you need specific information or advice?
Any and all input is welcome!

#### What are your goals and objectives?
Create, maintain and improve the exchange.

#### How will you evaluate project success?
What level of liquidity do we offer?
Do we support the assets that people want to exchange with TNB?

#### What risks should you plan to manage?
Security & Reliability:
- We use DigitalOcean's Apps Platform with failover and horizontal scaling.
- API keys / private keys are either encrypted by DigitalOcean's Apps Platform, handled by a trusted third party payment processor (such as Coinbase) or encrypted in our database using a key securely stored on the Apps Platform

Legal:
- Agreements have been written by a contract lawyer and will be independently evaluated.

Audit:
- All transactions are logged with timestamps and crypto addresses.

#### What are your milestones?
- Milestone 1 - UX ready (done)
- Milestone 2 - Backend API ready
- Milestone 3 - Security audit
- Milestone 4 - Market analysis & widespread adoption
- Milestone 5 - Public API for TNB <-> external currency exchange
- Milestone 6 - Handling of legal tender

#### Tell us about your team members:
Full Name, Slack Username, GitHub Username, LinkedIn, Role, Team Joining Date, Team Leaving Date, Account number

Mieszko Kycermann, Kycermann, @kycermann, https://www.linkedin.com/in/mieszko-kycermann-284b28194/, Founder of Mieszko.Exchange, -, -, f1decb80339a4bb6c089b77cbac553e23a6ca86b0cfc64adb8c8eb8f8b57d815

Santosh Kumar Baskaran, Mik, @Mik1337, https://www.linkedin.com/in/santosh-kumar23/, Infrastructure Developer, -, -, 880dc7caa719b9fcd5285491d9b1205875e8dec057af03c18f9edb6dcc07e2ed

Jared Furlow, Jared, @jdf221, https://www.linkedin.com/in/jaredfurlow, Infrastructure Developer, -, -, 84f45914a30e7428b3fe5ddf717ba05ab132d517c0e76c8be1a7e7d569b00b24

#### List the roles of any additional team members you would be looking for?

UX / Graphics designer :)

**Comment by manishram** [comment]
Hey @Kycermann , I really liked your project proposal. One of the best Project-Proposals.
Now you have to comment down here your **GitHub repository URL of the project**. You can provide an empty repository URL as well if you have not already started working on the project.

**Comment by manishram** [comment]
Project Github: https://github.com/Mieszko-Exchange/
