### ISSUE TITLE
TNB MMORPG

### ISSUE THREAD

**Issue by mrbusysky** [thenewboston-developers/Project-Proposals#108]
#### How would you describe your project?
TNB MMORPG
#### What problem does it solve?
Token sink for token lockup.

#### Who is the target market?
Gamers and crypto investors.

#### What do you think is the opportunity of this project?
To bring investors and active users into the network, also high lighting the chain's strengths against all chains that exist 

#### How does it integrate with thenewboston digital currency work?
We will be using the upcoming feeless transactions in our project to create items, in-game currency, and to facilitate trades for items.

#### Are there any competitors?
Not really, in the crypto space. There have been attempts but nothing that is remotely close to realtime.

#### Will, you need specific information or advice?
Not in particular I'm helping with the documentation and architecture of the chain. So I will know mostly how everything will work.

#### What are your goals and objectives?
Get a game to BETA release first then full launch to give the chain something to advertise its capabilities.

#### How will you evaluate project success?
How many network transactions are happening with the id of the game.

#### What risks should you plan to manage?
Possibility of high fee's for transactions as time goes on.

#### What are your milestones?

- Milestone 1 : Finalize scope
- Milestone 2 : Build story
- Milestone 3 : Environmental/ Items/Character designs
- Milestone 4 : Asset Creation
- Milestone 5 : Map creation
- Milestone 6 : Character modeling
- Milestone 7 : Quests
- Milestone 8 : Skill tree
- Milestone 9 : Crafting
- Milestone 10 : TNB login method
- Milestone 11 : TNB item creation logic
- Milestone 12 : Auction house
- etc..

#### Tell us about your team members:

- mrbusysky - Project lead/system architect/designer
- More: I'm willing to bring on others

#### List the roles of any additional team members you would be looking for?
- Map Designers
- Character designers
- Storyboard writers
-and more.

Generally people with game development knowledge of game creation.

As for a document about what will be made the game design document has been shown to Manish and we are working on a public list of upcoming features for the game. Which will be listed in our project folder.

**Comment by manishram** [comment]
@mrbusysky Great Project Proposal!! Please comment down here the Github Organisation/Repo link.

**Comment by mrbusysky** [comment]
https://github.com/orgs/TNB-MMO/dashboard
