### ISSUE TITLE
Recruiting Specialist

### ISSUE THREAD

**Issue by DemetrioOrnelas** [thenewboston-developers/Project-Proposals#113]
**How would you describe your project?**
My project can be defined as a mainstreaming and centralization of the recruitment/hiring process for thenewboston. I would like to serve as TNB’s own Talent Recruiter. This can be achieved through categorizing and pooling talent into an easily accessible and manageable “talent pool”. Part of this process would be the introduction of a full-blown recruitment system through outreaches both virtual and in-person, and a depository for resumes, portfolios, and linkedIn profiles. A large part of this project will be reporting and managing the volume of candidates that are applying, the number of positions being posted/requested, and the hire/disposition rates. This will all be achieved without the need of or reliance on CSR management systems through pivoting tables and manipulating data within excel reports. 

**Key components to managing the recruiting life cycle will be indicated below:** 
I.	Management of potential hires, future and expanding roles, and analytical review of hires/drop-off monthly.
a.	Management of potential hires
i.	Offer project leads the opportunity to submit a “position request” ticket. 
1.	Information required will include the desired starting date, flexibility in work availability, required/preferred experiences, and expectations of the role.
2.	This will allow the recruiting team to begin scouting candidates through referrals, LinkedIn, discord, reddit, slack, (indeed potentially), and more.
3.	The project lead will be able to see us update their ticket in real-time through a shared (locked) excel document, google drive or preferred application. 
a.	A method will be implemented to “hire-on” any chosen candidate while putting into reserve any candidates who applied but were not chosen. Communication will be provided to inform them of other open positions and build continued interest with thenewboston.
b.	Future and Expanding roles
i.	Aligned with other expectations and goals for TNB we will also want to advertise and build a reservoir of candidates for future upcoming positions that may not be immediately available. 
ii.	Current on-going project announcement!
1.	It would be beneficial to manage a log of current projects and announce every start/end of the week what is being worked on and announce any progress or micro updates.
c.	Data Analysis
i.	Metrics for tracking how many positions are opened, filled, the kinds of positions, and tracking methods.
1.	Information will be reviewed on a bi-weekly schedule

**What problem does it solve?**
A major concern is that most recruiting occurs internally, between those who have manually entered one of the many channels available. While this is partly effective many positions remain opened, talent becomes lop-sided for a particular role, or positions become filled that do not suit the particular abilities of a candidate. 
Another area of concern is being able to effectively communicate between all social platforms and cohesively advertise and close a position. Part of this project will be the capabilities of relaying cross-information between needs from reddit, youtube, discord, github, slack, etc. 
Additional problems will include the inevitable volume changes as TNB expands. A system that has been well rehearsed and productive will be important in the long run. As more and more people come on board an audit may never be necessary but important project information can be traced and recorded.

**Who is the target market?**
Students looking for one-off projects to apply to their resume’s and portfolios. Early career talent opportunities for those who are not necessarily field-experts and/or degree specialists. Any and all with interests and knowledge on cryptocurrency. Part of this project will be exploring who exactly is attracted to the role organically and what kind of interests and opportunity look for while we are recruiting. 

**What do you think is the opportunity of this project?**
The opportunity is a chance to create a cohesive and working recruitment and candidate database prior to and in expectation of a rise of interest. The opportunity will allow us to consistently gauge interest not only on the project itself but its ability to produce quantitative data for what people are willing to do. In addition this would be in collaboration with any outreach and communication efforts to build a cohesive message of values, expectations, and future. 

**How does it integrate with thenewboston digital currency work?**
In the world of cryptocurrency thenewboston is pioneering a community-based network that relies on and is driven by tasks. By helping guide interested parties to and towards where they would best apply their talents and abilities the effectiveness of the currency will also benefit. I believe being able to help and assist those with interest in participating find and enable them in their field that the digital currency will only become more successful. 

**Are there any competitors?**
Competitors would be any other company or organization that could utilize a developer, technical, non-technical, or otherwise any particular role that TNB advertises for. 

**Will you need specific information or advice?**
Specific information that I will require will be either a set standard in regard to what we already look for when hiring or enabling an interested party and how we would like to go about this in the future. Culture is important and I wouldn’t want to infringe on what is already set in-place unless we want to clearly delineate our future. For example 

**What are your goals and objectives?**
My goals and objectives are simplified below: 
1.	Begin a recruitment process that will engage with and promote thenewboston to a very large and untapped pool of candidates across the world. 
2.	Manage and analyze statistics such as but not limited to ; the amount of people looking for work, the kind of work they are interested in, their availability, and ensure that the population already working is dispositioned and on track for either new roles or different work.
3.	An important factor to the goals I would like to achieve is the simultaneous dismantling of the idea that a person’s potential is limited to one specialization or role. As more information is recorded and goals become clear, our candidate list will grow and as people complete tasks we will gain an understanding of someone’s potential to move through different tasks. 
4.	My final goal is to introduce a level of community and professionalism to working with thenewboston, the opportunities within cryptocurrency have value and are valued, many do not understand the potential there is to work with a project of this magnitude and how much of an asset it would be work with such an amazing group of people.

**How will you evaluate project success?**
Project success will be gauged primarily by our ability to fulfill position tickets and provide effective and concise data on how we are meeting project lead requirements. In addition project success will be measured on a monthly basis by how well our recruitment needs are met and how well we are able to integrate new members to their teams. 

**What risks should you plan to manage?**
Risks include managing so many different channels of communication. Part of the issues seem to be how well we communicate open roles across so many platforms. In addition, the volume can be expected to only increase as time passes. 

**What are your milestones?**
- Milestone 1:  Begin receiving and documenting ticket requests – end of February 
- Milestone 2: Setup and analyze reports for recruiting efforts, position requests, and quantitative data. ( back end ready) – 1st March 2021
- Milestone 3: achieve a recruiting format for active outward recruiting including the ability to create pamphlets, TNB quick start guide, and in general have a virtual and potentially in-person format for creating interest on a systematic and centralized format (front end ready)– 1st May 2021
- Milestone 4: begin having a consistent idea of hiring/onboarding goals and the ability to disposition and move position holders from finished tasks to being available for hire.  – June 2021
-Milestone 5: clear understanding of position/candidate requests and the ability to manage and fulfill ticket request within a rapid time end of summer 2021
Milestone 6: analytical data is capable of being digested and applied. Present and discuss the longevity of candidates, projects, and create insightful predictions of the future. – end of summer 2021
Milestone 7: Being able to host thenewboston in-person fairs and/or attending conventions to vet exposure and interest. 
Milestone 8: Actively communicating with Alumni who have worked on tasks or a governance level and build a lasting and fruitful community network. 

**Tell us about your team members**
Full Name – Demetrio Ornelas
Slack Username  - Demetrio Ornelas
GitHub Username - DemetrioOrnelas
LinkedIn : www.linkedin.com/in/demetrio-ornelas-405363b1 
Title : Recruiting Partner

**List the roles of any additional team members you would be looking for?**
I would be looking for at least 1 or 2 more recruiters who can assist me with outreach and supplying information such as resumes, LinkedIn accounts, and analyzing the data we will be reviewing. 
In addition to his it would be useful to have at least one other person when creating tables and graphs for analyzing and categorizing our open positions and position requests and eventually being able to present this information as well.

**Comment by manishram** [comment]
Hey @DemetrioOrnelas this proposal is very much like a new role in thewnewboston rather than the project. But your proposed role is what is in great demand in our community. So I'm going to close this issue. Please Reach me on Slack (**Slack Name: Manish**) so that we can discuss more on this.
