### ISSUE TITLE
NLP based learning companion for students

### ISSUE THREAD

**Issue by prem2282** [thenewboston-developers/Project-Proposals#12]
#### How would you describe your project?
[NLP driven learning companion. The idea is to help students to learn their text book content in a smart way. For school students, its kind of boring to read through all the text in their book especially when they are preparing for their examinations. In countries like India, text book usage is heavy and I don't remember a day without dosing off when I start to read my text book.

The  idea for the app is a follows.
1. A text book can be uploaded to the App.
2. The App will use Data science and Natural Language processing to create structured text content from the book.
3. For every lesson and its subsection, (or even for a given paragraph), the App will use NLP to create different ways of test formats automatically.   (A) Multiple choice Questions (B) Fill in the blanks (C) True or False type (D) Short questions and answers.
4. The app can also read out the complete section for the student to hear
5. The app can interactively voice out questions based the choice of the student and help them learn quickly.
6. The app can do any other learning app does like, keeping the leaderboard, reminding, etc.
7. Later the app can be integrated with voice assitants like Alexa to make learning more fun.
]

#### What problem does it solve?
[Reading a text book and automatically creating learning content that can be customized per students needs.

I already have built a Voice enabled Q&A app called quizmebuddy.com - I did this to help my daughter in Grade 5. 
I want to take it to the next level with the use of NLP and Machine learning.
]

#### Who is the target market?
[Students who use text books for their academics]

#### What do you think is the opportunity of this project?
[I believe, all though there are many learning apps available, this one is unique as it gives very unique experience for the students to learn exactly what they want to and not a generic content. Once we develop this process of reading any book and generating structured content, this can be a huge platform for students from anywhere in the world]

#### How does it integrate with thenewboston digital currency work?
[The users can buy subscriptions to the app through our digital currency]

#### Are there any competitors?
[There are many. But I have not come across one that can generate customized content based on text books]

#### Will you need specific information or advice?
[I will need help with structuring the project and advice on technologies to use. I am good in NLP and Machine learning, so I can take care of the same and guide the team. But for front end development and designing, need some experts ]

#### What are your goals and objectives?
[Create an app that will reach as many students as possible to make their academic learning fun and intiutive]

#### How will you evaluate project success?
[There are many stages involved. At every stage there will a success criteria. To start with, reading text book and splitting them into individual lesson. Then splitting individual sections. Then understanding the content and creating structure Q&A for different formats. Finally users using the app as a companion for their learning ]

#### What risks should you plan to manage?
[
1. Risk of not able to read text books properly.
2. Risk of not completing the task on time.
3. Risk of unavialability of resources.

There are many others that I should manage, but these are few coming to my mind right now.

]

#### What are your milestones?

- Milestone 1: Design approach for Text book reading - Dec -15 2020
- Milestone 2: Building NLP process to create structure content - Jan 30 2021
- Milestone 3: Creating customizable Q&A content from structured data - Mar 30 2021
- Milestone 4: Front end development - Apr 30 2021
- Milestone 5: Testing and deployment - May 15 2021

#### GitHub usernames, slack names and roles of all team members:
- prem2282 - lead developer.
other team members need to be identified. I need help in this.

Here is my slack id - U01FFR79A3B (Name is Prem Anand, email : prem2282@gmail.com)
https://app.slack.com/client/T07PJD1FZ/C07PJ5ETS/user_profile/U01FFR79A3B

**Comment by manishram** [comment]
Hey @prem2282 can you please change the title of issue with the name of your project? And also please provide details of your teammates for this project. If you don't already have teammates, just fill your details for now. We'll help you find teammmates for your project after that.

**Comment by prem2282** [comment]
> Hey @prem2282 can you please change the title of issue with the name of your project? And also please provide details of your teammates for this project. If you don't already have teammates, just fill your details for now. We'll help you find teammmates for your project after that.

thanks @manishram . I have done the same.

**Comment by manishram** [comment]
Hey, @prem2282 can you please add your slack name as well so that we can contact you. If you have not already joined thenewboston slack then please[ Click here](https://join.slack.com/t/thenewboston/shared_invite/zt-j7j4ie92-ADy7GL3KAzCwSlaAVoDKLw) to join.

**Comment by prem2282** [comment]
> Hey, @prem2282 can you please add your slack name as well so that we can contact you. If you have not already joined thenewboston slack then please[ Click here](https://join.slack.com/t/thenewboston/shared_invite/zt-j7j4ie92-ADy7GL3KAzCwSlaAVoDKLw) to join.

Hey @manishram - I have added my slack id in the proposal.
https://app.slack.com/client/T07PJD1FZ/C07PJ5ETS/user_profile/U01FFR79A3B

**Comment by Chrisha1212** [comment]
Hi @prem2282 Since you've mention that you need a front-end and designing expert would you state how many people and what are the qualification you needed to help you with this project.

**Comment by prem2282** [comment]
> Hi @prem2282 Since you've mention that you need a front-end and designing expert would you state how many people and what are the qualification you needed to help you with this project.

Hi @Chrisha1212, 
I will start with 1 ReactJs (also some exp with ReactNative) experienced developer. as the project gets some progress, few more with same skill set can be added.
Below are some key asks for Reach developer.
1. The react front end should be able to connect to cloud services like S3, dynamo db, IAM, Lambda (if we decide to go with AWS cloud)
2. Authentication through third party federation services like Google, Facebook etc.
3. React application should make use of Speech Synthesis API for voice enabled user interaction.
4. Payment gateway integration

For the back end, one advanced python developer experieced in NLP libaries (example: Spacy, NLTK).
The core of app is here.

Hope this helps.

**Comment by manishram** [comment]
Congratulations @prem2282 , your proposal is impressive. Please provide the repository link of your project. You can provide an empty repository link for now if you have not already started working on your project.
