### ISSUE TITLE
Escrow

### ISSUE THREAD

**Issue by dhakal0kushal** [thenewboston-developers/Project-Proposals#129]
#### How would you describe your project?
An escrow web-application for thenewboston. This application will act as a bridge between the escrow providers, the buyers, and the sellers.

#### What problem does it solve?
The problem is to get trusted escrow and avoid the scams that may happen in the near future.

#### Who is the target market?
Anyone who wants to buy/sell TNBC in exchange with other (crypto or international) currencies or products before the coin is in exchange.

#### What do you think is the opportunity of this project?
This platform can be a bridge between buyers and sellers. There will be a spike in the number of people wanting to buy TNBC before it's officially released and this platform can work as an exchange for that period of time.

#### How does it integrate with thenewboston digital currency work?
This service is, particularly for thenewboston.

#### Are there any competitors?
I find no application similar to this in the market made for thenewboston.

#### Will you need specific information or advice?
Of course. Should we make an MVP with plain Django for faster delivery or should we use REST with JS framework which will take time to complete?

#### What are your goals and objectives?
To prevent scams from happening while people are buying/selling TNBC. Perhaps this model can be used in future projects and other cryptocurrencies. The structure itself can be the same, just the name will change.

#### How will you evaluate project success?
The more people exchange their TNBC, the more successful this project will be.

#### What risks should you plan to manage?
If the escrow provider themselves turns out to be a scammer then it’ll be a hard time for us. We’ll have to screen people beforehand, as well as find trusted people in the community that will be open and willing to act as an escrow. Perhaps have them provide some kind of proof of identity if not active and/or have someone vouch for them.

#### What are your milestones?
- Milestone 1: Create MVP with Plain Django - 4th Mar 2021
- Milestone 2: Get responses and feedbacks from the target market - 18th Mar 2021
- Milestone 3: Decide Frontend framework and start working on the design - 18th Mar 2021

#### Tell us about your team members:
Full Name, Slack Username, GitHub Username, LinkedIn, Role, Team Joining Date, Team Leaving Date, Account number
Kushal Dhakal, Hussu, dhakal0kushal, https://www.linkedin.com/in/dhakal0kushal/, Project Lead, 02/18/2021, - , 22d0f0047b572a6acb6615f7aae646b0b96ddc58bfd54ed2775f885baeba3d6a

#### List the roles of any additional team members you would be looking for?
Frontend Developer
UX/UI Designer

**Comment by manishram** [comment]
Hey @dhakal0kushal your proposal is great!! Please provide your project's repo/organization URL here.

**Comment by dhakal0kushal** [comment]
Hi @manishram, i was not hoping for the response soo fast btw. Here's the link to the project's organization: https://github.com/tnbCrow
