### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by GabrielJPVS** [thenewboston-developers/Project-Proposals#13]
**How would you describe your project?**

**Enhancing and sharing to more people, the TNB Official Discord.**
Create a better and new place for the TNB users via Discord, Building a fun and very informative location for everyone, integrating every single TNB social-media in one place, bringing more information to more people, and, encouraging / guiding them, to participate and in the TNB project.

**What problem does it solve?**

This could help in integrating all TNB social medias in one place, because, right now, TNB has a total of 7 different social media’s (Slack, GitHub,  YouTube, Reddit, LinkedIN, Facebook, and Twitter) Discord has the potential, and it would be very useful if all of them were in a same place, letting everything much easier, but it's not needed to stop using Slack, for example, it is just going to funnel everything to discord bringing more information to the most people easier.
Besides that, the TBN Discord would also encourage new developers to start their projects and be hired via Discord, and then, participating and working on the project, creating a whole active community with Voice Chats, Categories including:
TNB announcements and new uploads, helping the project with server boosts, all Reddit (Which is already implemented by one of my suggestions: Redditor Bot.), app-ideas, design, developers, front-end, back-end, marketing, and so much more
It would also help with the moderation, guiding the right people to the right place, showing projects that they could work on and help with their already started projects, in a fun way.
And Finally, it could also share the project with new people, because, Discord has a total of +100 million users, and a lot of the users are coming from the new video, and they are only getting to know the project now, thanks to Discord,  so, improving the bots and integrations, would show it to more interested people on the TNB project.

**Who is the target market?**

All TNB app users, and, potential developers and users for the TNB.

**What do you think is the opportunity of this project?**

It is a great opportunity to improve the TNB Official Discord, showing the TNB to more people, having a better moderation, integrating all the social-medias, and in general, creating a better place for the community.

**How does it integrate with thenewboston digital currency work?**

As mentioned above, it would bring new members and create a better place for the community.

**Are there any competitors?**

N/A

**Will you need specific information or advice?**

For everything to work, me and my team would need to be part of the moderation Discord team, and maybe, new moderators.

**What are your goals and objectives?**

Make the TNB Community better, with new features, via improving the TNB Official Discord.

**How will you evaluate project success?**

I will evaluate project success when all the milestones are done, for example, get every single TNB user that is an interested developer on Discord, so we can guide, help, and etc., with ease.

**What risks should you plan to manage?**

Recently, many attacks and raids are happening in numerous Discord servers, to grief or completely destroy entire servers. I will manage so that everything is secure on discord, so that users personal information never be leaked.

**How many total coins are you requesting?**

Weekly payments with pay per day of 2800 coins. (https://thenewboston.com/project-proposals/funding)

**GitHub usernames, slack names and roles of all team members:**

- GabrielJPVS | @GabrielJPVS | Project Lead & Discord Bot Developer; Social Media Integration; Moderation.
- JunqueiraSafe | @Junqueira | Python Implementations Main Developer; Moderation.

#### Milestones:
[ANSWER]

**Comment by manishram** [comment]
Hey, @GabrielJPVS we changed the template a little bit and replaced **How many total coins are you requesting?** with your **project milestones** because most of the people are not sure of the former. So please update your proposal. And also in the teammate section, you don't need to provide the roles your teammates have in Thenewboston community but the roles they will have in **your project**. So please update them too.

**Comment by manishram** [comment]
Hey @GabrielJPVS, 
1. Change issue title with the name of your project
2. Add your project milestones

Once done, we are good to go.
