### ISSUE TITLE
KnowledgePath? ExpertPath? Not sure yet. These names are taken, but we'll find another one.

### ISSUE THREAD

**Issue by Mirch** [thenewboston-developers/Project-Proposals#135]
#### How would you describe your project?
This will be a curator/aggregator of resources that can be used to follow a certain career path (e.g. JavaScript full-stack developer). The actual form it will take is a GitHub organization with multiple repositories divided by programming language/tech stack, with multiple divisions under each repository (e.g. the .NET repository could include web development, cloud development, machine learning, etc.). The resources will be arranged in a way that makes sense for a new learner.

Each division could include not only resources, but open-source projects that are available for collaborations.

#### What problem does it solve?
For the users, having to find the right resources on a certain subject. 
For TNB, finding talent to contribute on different projects.

#### Who is the target market?
People who want to learn a certain stack.

#### What do you think is the opportunity of this project?
While there are other aggregators for different programming languages/stacks out there, that's all they are - aggregators. Here, we aim to create learning paths for each stack and continuously verify for updates on each resource. 

#### How does it integrate with thenewboston digital currency work?
The organization will accept donations in TNB, and will direct new talent to different TNB projects.

#### Are there any competitors?
It's hard to define competition in this space, but no other free options seem to exist for this purpose.

#### Will you need specific information or advice?
Not for now.

#### What are your goals and objectives?
Creating a space for people to be able to find the right resources for their learning path.

#### How will you evaluate project success?
Number of stars/forks/watches on each repository.

#### What risks should you plan to manage?
- Resources disappearing/being moved
- Some content being updated as the tech stack progresses 

#### What are your milestones?
- Milestone 1 : Setup the guidelines and repo structure
- Milestone 2 : Create the right communications/marketing strategy
- Milestone 3: Have at least 3 paths for a tech stack/programming language.

#### Tell us about your team members:
Full Name, Slack Username, GitHub Username, LinkedIn, Role, Team Joining Date, Team Leaving Date, Account number
Mircea Teodor Oprea, Mircea Teodor Oprea, Mirch, mircea-oprea, Project Manager, 23.02.2021, -, dc3eb7a93238a4e691817d294c97fa372748807c473130901b71b819032a2faa

#### List the roles of any additional team members you would be looking for?
- Marketing/Communication strategist - someone that will define a plan for how to reach more people and what platforms to use for doing so.

**Comment by manishram** [comment]
@Mirch please comment down your project repository here. And also make a PR with your project details here: https://github.com/thenewboston-developers/Project-Proposals/tree/master/projects

**Comment by Mirch** [comment]
https://github.com/champath/guidelines
