### ISSUE TITLE
Coinratecap - Project Proposal

### ISSUE THREAD

**Issue by Francaolisa** [thenewboston-developers/Project-Proposals#14]
#### How would you describe your project?
[ Coinratecap has been in existence for 2years now and is a bit popular. But presently, we want to rebuild the entire website on Django and node.js, as is presently lacking a lot of tools and our inability to list a coin because we use coinmarketcap api which makes it impossible to list a coin or an exchange. 
So the plan is to rebuild the entire site from scratch and make provisions for all the necessary tools that need to be there.

For the new site, Coinratecap will list prices of all cryptocurrencies listed in a crypto exchange, event calenders, crypto portfolios, ratings, and exchange lists. We will also make provisions for free API's for people that want to use it on their sites. ]

#### What problem does it solve?
[ It will solve the problem of fake volume, quick removal of dead/scam coins, and provides all-in-one tools for users.]

#### Who is the target market?
[ My target market is cryptocurrency/blockchain enthusiasts which are found all over the world. ]

#### What do you think is the opportunity of this project?

[ The future of successful project management involves doing the right projects—not just doing projects right. Therefore, there's a great opportunity in this blockchain/cryptocurrency era if we place more value on solving a problem, and that is what Coinratecap is out for -  to solve problems using an algorithm to dictate fake volumes and scam-related projects.]

#### How does it integrate with thenewboston digital currency work?

 [ Once Coinratecap strike a partnership with Thenewboston, it will bring sustainable positive change to both parties;
1.  Presently, Coinratecap is making plans to accept TNB coin on the website for advertisement.
2.  We will accept TNB coin from our clients for our other services that we provide in our parent company MFTECH GLOBAL VENTURES, which provide services like web development and marketing.
3.  Coinratecap will be used as a marketing tool for Thenewboston. ]

#### Are there any competitors?

[ Yes, there are. liveoinwatch.com and coingecko.com ]

#### Will, you need specific information or advice?

[ Surely, as work progress, there will be a need for it. ]

#### What are your goals and objectives?

[ My goal is to make provision for tools that can help crypto enthusiast navigate through.
My objectives are to use an algorithm that will fight against fake volumes, crypto scam projects, educate and provide an all-in-one tool for users. ]

#### How will you evaluate project success?
[ I will evaluate the success when are the milestone and objectives are successfully met. ]

#### What risks should you plan to manage?

[ The risk I plan to manage is a frequent upgrade, web security, and attacks on servers.. ]

#### What are your milestones?

- Milestone 1 : UX/UI ready - 1st Jan 2021
- Milestone 2 : Front-end ready - 20th Jan 2021
-Milestone 3:  Backend ready- 2nd March 2020
-Milestone4:  Andriod/IOS app ready- 1st April, 2020
- etc..

#### GitHub usernames, slack names, and roles of all team members:

Github - Francaolisa
Slack name - @Francisca -SM Manager

**Comment by manishram** [comment]
Congratulations @Francaolisa , we liked your project proposal. Now you need to provide your project repository link (You can comment down here). You can provide an empty repository link also if you have not started working on your project yet.

**Comment by Francaolisa** [comment]
> Congratulations @Francaolisa , we liked your project proposal. Now you need to provide your project repository link (You can comment down here). You can provide an empty repository link also if you have not started working on your project yet.



> Congratulations @Francaolisa , we liked your project proposal. Now you need to provide your project repository link (You can comment down here). You can provide an empty repository link also if you have not started working on your project yet.

Thank you. Should I provide project repository link here?

**Comment by manishram** [comment]
Yes, just comment down your repository link here.

**Comment by Chrisha1212** [comment]
Congratulations @Francaolisa I will start Connecting you with your potential team as well.

**Comment by Francaolisa** [comment]
> Congratulations @Francaolisa I will start Connecting you with your potential team as well.

Thank you Chrisha1212

**Comment by Francaolisa** [comment]
> Congratulations @Francaolisa , we liked your project proposal. Now you need to provide your project repository link (You can comment down here). You can provide an empty repository link also if you have not started working on your project yet.

Here’s my repo link : https://github.com/Francaolisa/Coinratecap

**Comment by manishram** [comment]
Hey, @Francaolisa your project has been added to the repository. 
**Coinratecap**: https://github.com/thenewboston-developers/Project-Proposals/tree/master/projects/14-Coinratecap

**Comment by Francaolisa** [comment]
> Hey, @Francaolisa your project has been added to the repository.
> **Coinratecap**: https://github.com/thenewboston-developers/Project-Proposals/tree/master/projects/14-Coinratecap

Okay thanks.

**Comment by Francaolisa** [comment]
> Hey, @Francaolisa your project has been added to the repository.
> **Coinratecap**: https://github.com/thenewboston-developers/Project-Proposals/tree/master/projects/14-Coinratecap

Just in case, here's a new project link https://github.com/coinratecap

> > Congratulations @Francaolisa , we liked your project proposal. Now you need to provide your project repository link (You can comment down here). You can provide an empty repository link also if you have not started working on your project yet.
> 
> Here’s my repo link : https://github.com/Francaolisa/Coinratecap

Just incase, here's a new project link https://github.com/coinratecap
The previous one has been deleted.
