### ISSUE TITLE
TNB FAUCET

### ISSUE THREAD

**Issue by mrbusysky** [thenewboston-developers/Project-Proposals#141]
#### How would you describe your project?
A faucet that allows people to put their wallet address in and get coins.

#### What problem does it solve?
Distribution

#### Who is the target market?
Crypto world, bukys followers, and so on, people looking to find a way in with no skillset.

#### What do you think is the opportunity of this project?
It will allow us to spread coins to people early on, the more people we have holding the coin the better. Also, it's a way to educate people of the chain in steering them into the right channels like the main website, discord, and Github. It would also allow any project to giveaway coins.

#### How does it integrate with thenewboston digital currency work?
Basically just pays people out to their wallets.

#### Are there any competitors?
None

#### Will, you need specific information or advice?
Nope

#### What are your goals and objectives?
To spread the coins to as many people as we can.

#### How will you evaluate project success?
If we can get tens of thousands of people holding the coins.

#### What risks should you plan to manage?
Normal bot abuse and people trying to claim on multiple accounts.

#### What are your milestones?

- Milestone 1: Scope 
- Milestone 2: Ui/UX
- Milestone 3: Landing page
- Milestone 3: Setup cAPTCHA
- Milestone 4: Generate wallet page
- Milestone 4: Backend to send coins

#### Tell us about your team members:
* mrbusysky - Team leader, project scoper, the project owner.

#### List the roles of any additional team members you would be looking for?
* Python developer 
* React developer
* Designer
* and more

**Comment by itsnikhil** [comment]
@mrbusysky We have already made a Faucet bank.centralindia.cloudapp.azure.com/faucet/

You can close this issue

**Comment by mrbusysky** [comment]
Won't be closing it we need a faucet script anyone can spin up and modify easily without removing features they don't need. A base script that also has important features like wallet creation and so on.

**Comment by itsnikhil** [comment]
@mrbusysky Blockchain Explorer is open source and if you just want the script and you can see our repository and get the code.

I would insist you to close this issue or do it without asking for thenewboston to fund this ideas as they have already paid us the coins for doing thie exact same thing. They should fund two projects doing the same thing.

**Comment by itsnikhil** [comment]
Regarding "A base script that also has important features like wallet creation and so on" I would say do you even have any idea what a faucet is? You should read FAQ from the site 😂 http://bank.centralindia.cloudapp.azure.com/faucet/

**Comment by mrbusysky** [comment]
I'm well aware what a faucet is. And wallet creation on a faucet is pretty normal since many have logins. And having to strip your project just to get what I need don't seem appealing.

**Comment by mrbusysky** [comment]
Once the main website is done, we will work on this. Had to get something up temporarily. I Will make a repo around Monday or so.

**Comment by mrbusysky** [comment]
https://github.com/TNBFAUCET/tnb-faucet-script

**Comment by manishram** [comment]
https://github.com/thenewboston-developers/Project-Proposals/tree/master/projects/141-TNB-FAUCET

**Comment by mrbusysky** [comment]
still being scoped for after the current manual faucet round going on
