### ISSUE TITLE
TNB-DISCORD BOT

### ISSUE THREAD

**Issue by mrbusysky** [thenewboston-developers/Project-Proposals#143]
#### How would you describe your project?
A bot that can be used by all discord servers to verify users are who they are with a bunch of other features.

#### What problem does it solve?
Discord verification and token spreading.

#### Who is the target market?
Discord users

#### What do you think is the opportunity of this project?
Expand tnb's influence in the crypto space.

#### How does it integrate with thenewboston digital currency work?
Allows people to be verified which will come in handy with top banks and government people.

#### Are there any competitors?
No none at all.

#### Will you need specific information or advice?
No, we are fine,

#### What are your goals and objectives?
To allows people to connect to the tnb chain via discord.

#### How will you evaluate project success?
By features complete

#### What risks should you plan to manage?
There is no real risk.

#### What are your milestones?

- Milestone 1 : Scope
- Milestone 2 : Feature development
- Milestone 3 : Beta tests
- etc..

#### Tell us about your team members:
mrbusysky - Team leader, project scoper, the project owner.
FilterUnfiltered- Main bot developer

[ANSWER HERE]

#### List the roles of any additional team members you would be looking for?
Not currently no.

Early scope:
https://docs.google.com/document/d/18Z2D8WZlf6MKgKFa_Tdevk3S_dbYQEsX0xHRbMdQUVQ/edit?usp=sharing

**Comment by mrbusysky** [comment]
https://github.com/Keysign-Wallet/TNB-BOT

**Comment by manishram** [comment]
@mrbusysky make a PR with your project details to the Projects Folder.
