### ISSUE TITLE
Blockchainafrica

### ISSUE THREAD

**Issue by Francaolisa** [thenewboston-developers/Project-Proposals#155]
#### How would you describe your project?
Blockchainafricas' goal is to educate and share information in blockchain and cryptocurrency across the world especially Africa.

#### What problem does it solve?
People who have no access to accurate information gathering.

#### Who is the target market?
Anyone interested in blockchain and cryptocurrency.

#### What do you think is the opportunity of this project?
People who have ideas to share but have no means of sharing. Also, we plan on integrating portfolios for crypto enthusiasts.

#### How does it integrate with thenewboston digital currency work?
It will be a means of promoting Thenewboston.
We will constantly write content related to Thenewboston and have the developers and Bucky interviewed when the project is launched.

#### Are there any competitors?
Yes

#### Will you need specific information or advice?
[Yes, I welcome any suggestion,

#### What are your goals and objectives?
My goal is simply to educate and share useful information with the world.

#### How will you evaluate project success?
When we achieve the first milestone.

#### What risks should you plan to manage?
Web security.

#### What are your milestones?

- Milestone 1 : Graphics design - May 30th, 2021
- Milestone 2 : Writing- May 30th,2021
- etc..

#### Tell us about your team members:
Full Name, Slack Username, GitHub Username, LinkedIn, Role, Team Joining Date, Team Leaving Date, Account number
None for now. I Will add a few when approved.

@francisca

#### List the roles of any additional team members you would be looking for?

NOTE:  This project is already live - blockchainafrica.io
Just looking for a non-Technical team who will contribute content, graphics designers, and social media managers.

**Comment by manishram** [comment]
@Francaolisa can you please explain a little bit more clearly which kind of content you will be sharing? Is it different from a blog site?

**Comment by Francaolisa** [comment]
I share contents related to Blockchain, cryptocurrency, technology. And we are about starting video interviews for startups and crypto influencers.

**Comment by Francaolisa** [comment]
Milestone updated

**Comment by Francaolisa** [comment]
https://github.com/Blockchainafrica-io/Website

**Comment by e-kibet** [comment]
Interesting idea, How can i contribute to this open source project?

**Comment by Francaolisa** [comment]
> Interesting idea, How can i contribute to this open source project?

What are your skillset? Currently there’s an open position for a good SEO analsyt.

**Comment by e-kibet** [comment]
Hi Thenewboston-Developers/Project-Proposals,

I am ready for that position. Give me more details on this.


Kind Regards,
EVANS

**Comment by Francaolisa** [comment]
Send details of your past work by joining Thenewboston slack channel, then message me with your details @francisca -Sm Team Lead
