### ISSUE TITLE
Project Proposal: Apt repository

### ISSUE THREAD

**Issue by Distill-pixel** [thenewboston-developers/Project-Proposals#16]
#### How would you describe your project?
APT repository from which a user can install TNB's programs on Debian based Linux distro's

#### What problem does it solve?
It makes updating the application much easier, it makes TNB's programs more available and it's just going to be more organized.

#### Who is the target market?
Linux users running a Debian based distro.

#### What do you think is the opportunity of this project?
Gathering dependencies and updating the application will become easier for users, plus they won't have to execute an AppImage etc. every time but rather they can run a simple terminal command in order to start the application (it actually depends on the application). Agreed, shortcuts do exist but they are quite hectic in my opinion.

#### Are there any competitors?
We don't really have competitors.

#### How does it integrate with thenewboston digital currency work?
Makes the account manager etc. more accessible to Linux users.

#### Will you need specific information or advice?
Not really, if we face issues while debianizing projects, we will contact the people assigned to that project on assistance.

#### What are your goals and objectives?
Our goal is to centralize one place where Debian based distro users can get TNB applications etc. from.

#### How will you evaluate project success?
All planned packages to go on the repo work on all distro's support is given for.

#### What risks should you plan to manage?
Builds not working on some Linux distro's. We plan on doing tons of testing before pushing out builds, but in case we miss something, we will always be on the lookout for issues on the repo.

#### What are your milestones?
- Milestone 1: Building all the programs to obtain .deb files and creating an APT repo that can maybe accessed by a URL like apt.thenewboston.com and adding all the packages to it by December 20th

#### GitHub usernames, Discord names and roles of all team members:

- Stellaris @distill-pixel Stellaris#0001 Developer, project lead
- OMG_ @charliea21 OMG_#0001 Developer, project lead

**Comment by manishram** [comment]
Hey, @Distill-pixel you removed two questions from your proposal:
1. What do you think is the opportunity of this project?
2. Are there any competitors?
Please add them back and provide the respective answers.

**Comment by Distill-pixel** [comment]
Oh wow, I accidentally must've removed them.

Question 1: Gathering dependencies and updating the application will become easier for users, plus they won't have to execute an AppImage etc. every time but rather they can run a simple terminal command in order to start the application (it actually depends on the application)
Question 2: We don't really have competitors.

**Comment by manishram** [comment]
Congratulations @Distill-pixel , we liked your project proposal. Now you need to provide your project repository link (You can comment down here). You can provide an empty repository link also if you have not started working on your project yet.

**Comment by Chrisha1212** [comment]
Congratulations @Distill-pixel

**Comment by Distill-pixel** [comment]
Thank you, and great!
This is the repository: https://github.com/Distill-pixel/tnb-apt-repo
For now, we will be putting the apt repository on our own personal server, on demand we will switch servers if needed.
We will also need a DNS record(s) on the tnb domain that points to our server so people can reach the repository (apt.thenewboston.com)

**Comment by manishram** [comment]
Hey, @Distill-pixel congratulations!! has been approved. Can you please verify [team.md](https://github.com/thenewboston-developers/Project-Proposals/blob/master/projects/16-TNB%20Apt%20Repository/team.md) have correct team details?

**Comment by Distill-pixel** [comment]
Yes, you can actually change the looking for more teammates to yes as we don't mind more maintainers.

**Comment by Distill-pixel** [comment]
Hi! Should we support Ubuntu versions from 16.04 and onwards or 18.04 and onwards as 16.04 has been discontinued long ago, 18.04 and 20.04 are the current LTS versions that are still getting updates and are supported. We will not build packages for <16.04 as those versions of Ubuntu are really old.

We will build the account-manager project for arm64 (Ubuntu, Raspbian beta), armhf (Ubuntu, Raspbian), i686 and amd64 and there will be a build for Debian Buster too.

**Comment by manishram** [comment]
Go for 16.04 and onwards.

**Comment by Distill-pixel** [comment]
Alright, by the way we will have to extend our deadline's as we are facing some issues.

Our updated goals:
15th January: Server, APT repo and certificate setup
30th Feb: Builds of potential applications added to the repo and testing starts on stellaris.lol
15th March: Proposal for the APT subdomain on thenewboston.com and production release

**Comment by manishram** [comment]
Hey @Distill-pixel can you make a PR to https://github.com/thenewboston-developers/Project-Proposals/blob/master/projects/16-TNB%20Apt%20Repository/milestones.md with updated milestones.

**Comment by Distill-pixel** [comment]
Alright, sorry for the delays, we have started the work. I'll make the PR rq.

**Comment by Distill-pixel** [comment]
Update, we got further delayed but we've built a .deb file for 16.04 and onwards. We're currently working on the APT repo. We're going to need some resources soon, i.e an A record on thenewboston.com and maybe more.

**Comment by Distill-pixel** [comment]
The .deb file is for the account manager. It works fine, no issues encountered so far.

**Comment by manishram** [comment]
That's great!!
Hey, @Distill-pixel please join slack as soon as possible, and please ping me there. My slack name is Manish.

**Comment by Distill-pixel** [comment]
Alright
