### ISSUE TITLE
Auctioning App

### ISSUE THREAD

**Issue by whitelionx** [thenewboston-developers/Project-Proposals#18]
#### How would you describe your project?
- Our project is an Auctioning Web App that allows the user to auction items using the TheNewBoston (TNB) Coins.

#### A short description of how the app would run:
- The seller would upload his item which would need to go through initial validation by the staff in order for the items to be legit for the auction to happen. After the successful auction, the site takes a certain coin amount as a fee for the validation process in order to keep the project running.
- The buyers after registering to the site can buy auctioning credits with their actual coins, that way when we receive their payment we give them these and if someone wants to retrieve their coins he just exchanges the credits back to coins, the transaction happens and the seller/buyer gets coins back to his account, that is safer for us because we will always have the info on our side how much he has and it would be easier for us to just check on our side hey how much credits does this user have, if he has a valid amount to bid then he can bid, it would be problematic otherwise if someone tries to cheat with his amount on the account manager app and trick the app or the seller, so for security reasons we believe that this is, for now, a safe route for us to go.
- Just like in real life the highest bidder would get the item and the credits would be transferred to the buyer minus the validating fee our staff had to go through.

![image](https://user-images.githubusercontent.com/31674307/100552252-49cb5180-3286-11eb-983f-3fde96ee493d.png)

#### What problem does it solve?
- It solves the issue for non-IT people to start earning and using the coins in a meaningful way. It would also increase the number of coins in circulation.

#### Who is the target market?
- Everyone

#### What do you think is the opportunity of this project?
- As the first trading app that will use TheNewBoston cryptocurrency, this provides us with a great opportunity to increase the circulation of coins between Developers and Non-Developers. At the moment only Tech-Savy people are able to gain TNB coins, but our app provides an opportunity for anyone else that isn't tech-savvy to be able to trade items and gain coins while also giving "value" to the cryptocurrency.

#### How does it integrate with The New Boston digital currency work?
- As mentioned above this app completely wraps around The New Boston cryptocurrency as a digital payment form for selling and buying items.

#### Are there any competitors?
- In terms of The New Boston cryptocurrency there are none.

#### Will you need specific information or advice?
- Not much except for security & privacy probably

#### What are your goals and objectives?
- Get the coins out on the market so it can gain traction thus get value 
- Allow everyone to interact with The New Boston cryptocurrency

#### How will you evaluate project success?
- Expansion into different product sections, digital and physical 
- User base growth 
- Contribute to The New Boston community

#### What risks should you plan to manage?
- Security 
- User integrity 
- User privacy 
- Validity of each and every auction from both sides (Seller and Buyer)

#### What are your milestones?
- Hiring Phase 
- Discovery Phase (Planning and evaluating the tasks for the project) 
- Designing Phase (UI/UX Designers prepare the components for the project) 
- Architecture phase (Decide/Construct a certain architecture for the Project) 
- Development of the components & logic which are going to be integrated into the website

#### Tell us about your team members:
- As for now we have no set members as we want to get the approval for the project after that we start the official hiring process and deciding on the actual team but yeah there is one more Frontend guy beside me and we want to make this product a good one so we might even need more people than mentioned below.
- If I have to mention at least there are:
  - Me - Frontend - slack: Nine - GitHub: @whitelionx 
  - Din - Frontend - slack: DinShpati - GitHub: @DinShpati 

#### List the roles of any additional team members you would be looking for?
- 2 Backend Developers (Preferably one to be the lead for the backend side of things) 
- 1 FE Lead 
- 1 QA 
- 1-2 UI/UX Designers
- Maybe it turns out we need more based on the upcoming work that will need to be done

**Comment by manishram** [comment]
Congratulations @whitelionx , we liked your project proposal. Now you need to provide your project repository link (You can comment down here). You can provide an empty repository link also if you have not started working on your project yet.

**Comment by whitelionx** [comment]
@manishram https://github.com/whitelionx/auctioning-app I will add the code once I have certain things ready and hired people

**Comment by manishram** [comment]
Hey, @whitelionx congratulations!! your project has been added to thenewboston repository. 
[Auctioning App](https://github.com/thenewboston-developers/Project-Proposals/tree/master/projects/18-Auctioning%20App)
