### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by ashieY** [thenewboston-developers/Project-Proposals#2]
#### How would you describe your project?
[A tutoring platform that makes the lives of educators easier by handling scheduling and lesson planning and makes the lives of people easier by making it easy to find the specific help and education they need from experts.]

#### What problem does it solve?
[There are many platforms where you can find courses and maybe tutors, but there aren't many platforms where a person or organisation can hire tutoring services of a person for themselves or a certain number of people. The danger of watching tutorials is that people often get stuck in a false progression feedback loops where they feel as if with every tutorial they are getting better but in reality they are not, the solution to this would be doing your own projects but this can be quite difficult when one encounters a problem that they cannot solve especially when they cannot ask the question properly, our platform brings to gather the best teachers in specific areas of any field and allows you to hire out their time for teaching or help with anything you are struggling with. The common problem you hear amongst educators is earning potential and scalability. We give each educator the ability to set the number of students they want per class and different price tiers that vary for people who want a one on one. This makes their earning potential per hour much hire and their lessons more scalable.]

#### Who is the target market?
[People who need  tutoring, a person to person education environment  or a more personalised way of learning where they can ask question and have the teacher actively engage with them]

#### What do you think is the opportunity of this project?
[This project will integrate with other platforms, we are not replacing platforms like zoom or meet but rather we are working with them. By using bots and other tools we able to coordinate a schedule between different platforms for the educator to maximise their time and quality of education for example the app will have access to the calendar of all educators and they will specify periods they want to use for tutoring our app will then allow people to hire certain time slots and our app will update the calendar of the educator and notify them on their next tutoring session, we could build out a feature that is able to also schedule the environment for example create a zoom and send the login credentials to the person who bought the time slot.]

#### How does it integrate with thenewboston digital currency work?
[Educators Will charge fees according to the newboston currency given that the average hourly pay of tutors in dollar terms is well known the amount of coins a teacher wants per session will generally be converted by the buyer as the dollar value of average hourly tutor hence helping to assign the currency a value]

#### Are there any competitors?
[Yes, but there is no clearly dominant company in this space and the market is largely untapped but growing at fast rates due to Covid-19 lockdown measures. A notable competitor would be free-lancing websites but they are to broadly focused and lack the scheduling tools that this app will have that unlocks the full potential of all educators on the platform.]

#### Will you need specific information or advice?
[I am not as technical in programming, I only program really basic iOS Apps as I am still at the beginning of my programming career. I want to first try to build out an MVP on my own to test whether people would really want to use this. I will need advice on what programming stack I should use and what technical things i need to know going into the project for example how to build a bot and so forth. I am a decent programmer and I think I can pickup a new language quickly. When the MVP has been built and the idea validated. I will look for a more experienced programmer to improve my code and add more complex functionality. If i struggle to build the MVP I will use the advice and information you give me on how to build this to find a competent programmer who can build it properly]

#### What are your goals and objectives?
[I personally want to see this platform come into existence because its something I wish existed right now, I would love to offer my time for free to teach people something or hire someone that could teach me something new like a new language or hire a person to tutor students who are in need of the help. My broader vision is to create a platform globally accessible that allows anyone to get any help they need in various subjects and also unlock the power of actively learning through tutoring.]

#### How will you evaluate project success?
[The app has to be broken down into individual checking points. The first thing that we must be to built out is the ability to list a tutoring services as per individual, then the ability to rate the individual, followed by scheduling functionality. From a user stand point success will be evaluated by number of sessions on the platform as we continuously evaluate what the most common use cases for the platform are and any additional metadata. I am currently working on a product roadmap for each feature added and the design iterations that will occur. If you approve the project I will be more then happy to share the entire roadmap.]

#### What risks should you plan to manage?
[There is the risk of the platform not getting any users but I believe we can leverage the already existing community of teachers within the thenewboston to offer their services on the platform at their own price. To get initial users we can coordinate with organisations that provide education for free to children and we can help them during COVID-19 with its lockdowns, while we work on perfecting the platform for wider adoption. This app has a very Charitable focus but its not a charity app but rather a for profit one. I came across the idea for this app after hearing complaints from underprivileged children who did not have access to teachers during lockdown thus I thought it would be neat to include a charitable aspect to the app for social good.]

#### How many total coins are you requesting?
[200 000 up until MVP validation point, additional coins maybe needed to hire an experienced developer to make improvement to code and add more complex features]

### Additional
[I came across an idea for an app that rewards people based on how answered a given question the best, I thought the idea was quite neat and I think it can integrate well into this app for people who do not necessarily need tutoring help but have a question that needs answering from an expert. The community has multiple people focused on education that will embrace this platform}

GitHub usernames and roles of all team members:
- buckyroberts - Lead Developer
- kristykjlee - Lead Design
- etc...

**Comment by manishram** [comment]
Hey @ashieY 
Please join **thenewboston slack**: https://thenewboston.slack.com
Developer channel: **#developers**

There you can find developers who may be willing to help you with your project. Meet them, discuss your project, and come up with your team. It's always good to have people on your team who are specialized in a particular domain ( like UI/UX design, Backend-developer, Front-end developer, etc. ). This increases the chance of success for a project.

And then update your project proposal with the **GitHub username** and **role of the team members**.
