### ISSUE TITLE
BLACKWIDOW

### ISSUE THREAD

**Issue by kamal2222ahmed** [thenewboston-developers/Project-Proposals#25]
#### How would you describe your project?
crawl a website starting from home page, Crawl all the pages on the web site following the links

#### What problem does it solve?
A11Y ( Accessibility ) , So when we crawl, we would create a list of URLs / End Points and we can run accessibility verification on each URL by using something like aXe
#### Who is the target market?
Website Developers

#### What do you think is the opportunity of this project?
508 Conformance

#### How does it integrate with thenewboston digital currency work?
not sure
#### Are there any competitors?
yes, e.g. Compliance Sheriff

#### Will you need specific information or advice?
i tried with Apache Nutch, but having difficulty just installing and using Nutch in Docker

#### What are your goals and objectives?
Open Source this tool

#### How will you evaluate project success?
Community following, and adoption

#### What risks should you plan to manage?
False Positives

#### What are your milestones?

- Milestone 1 : UX/UI ready - 1st May 2021
- Milestone 2 : Front-end ready - 20th Dec 2021
- etc..

#### List the roles of any additional team members you would be looking for?
none

**Comment by manishram** [comment]
@kamal2222ahmed your project needs to be connected to thenewboston in some way.
**Rules and Guidelines:** https://thenewboston.com/project-proposals/rules
