### ISSUE TITLE
O3one

### ISSUE THREAD

**Issue by sawicnenad** [thenewboston-developers/Project-Proposals#28]
#### How would you describe your project?
O3one (pronounced as "ozone") - a web-application intended for the chemical industry in EU, EEA (=European Economic Area) and CH (=Switzerland) that must comply with the REACH (<a href="https://echa.europa.eu/regulations/reach/legislation">click me</a>) or similar legislations that regulate the use of chemicals at the workplace settings. The main use of O3one would be to support the enterprises in performing the chemical exposure and risk assessments using different statistical and physical-chemical models. Some of the models that would be included in the application are already recommended for this purpose by the European Chemicals Agency (ECHA).

#### What problem does it solve?
It is well known that the statistical models (<a href="https://www.echa.europa.eu/documents/10162/13632/information_requirements_r14_en.pdf">click me for more information</a>) are not fully validated and that their predictions are thus uncertain for some exposure conditions. ECHA thus recommends the enterprises to run exposure assessment using different models in order to have a better overview of different predictions and, therefore, different aspects of exposure. This task is very time consuming and expects some skills from the users.  If, for example, in an enterprise must perform exposure assessment for 100 chemical mixtures (each containing ~10 components) in three models, this would mean 100x10x3 = 3000 exposure assessments. 

Finally, the goal of our project is to facilitate process of exposure/risk assessment. The project intends to cover the following tasks:
<ol>
<li>Re-program exposure models recommended by ECHA under a unique tool</li>
<li>Provide the possibility to upload/import whole databases with chemicals</li>
<li>Enable O3one to automatically interpret chemical data and exposure conditions and generate input entries for the statistical models</li>
<li>Generation of numerical exposure results and graphical visualisation of the risk posed to human health</li>
<li>Implementation of novel machine-learning models</li>
<li>etc (ideas welcome)</li>
</ol>

#### Who is the target market?
Chemical industry, importers of chemical products and authorities dealing with the chemical regulations in EU/EEA/CH and potentially USA (to be considered).

#### What do you think is the opportunity of this project?
To my best knowledge, there is no such tool that allows the industry to perform such in-depth exposure assessments, provides user-friendly chemical data management and keeps track on which exposure conditions may pose risk to human health. The industry in all countries must comply with the chemical regulatory laws, which oblige them to perform exposure/risk assessments either by measuring the exposure (extremely expensive) or by applying the modelling approach (cheap alternative).

#### How does it integrate with thenewboston digital currency work?
TheNewBoston (TNB) currency would be used as the payment currency by the end-users. Although free version would be supported, premium users would need to subscribe for advanced features (e.g. large volume of data or use of machine-learning methods). While under development, the project could be support with TNB donations.

#### Are there any competitors?
Yes. However, most of the competitors offer limited experience, compared to the features enumerated above. The major competitor is Stoffenmanager (<a href="https://stoffenmanager.com/">click me</a>) with a subscription fee ranging from 500-3000 € per year per user. Providing the listed features above at lower price would solve the competition issue.

#### Will you need specific information or advice?
To be discussed. Likely help on how to recruit people that would be good match for this kind of project

#### What are your goals and objectives?
The very first (asap) goal is a web application covering the most of the ideas given above. It would be of great importance to attract the industry managers and engineers to try already alpha version of the tool. We must listen industry and their needs! This would help the developers to modify, if possible, some aspects  of the tool before beta and version 1. Otherwise, it would help the developers to know what version 2 should do better.

#### How will you evaluate project success?
By the number of end-users and the extent of their involvement in our project. This is why it would be important to have them somehow involved from the beginning. For this, of course, it would be very important to have a good marketing strategy.

#### What risks should you plan to manage?
From technical perspective, the good track of the project development is essential. It is important that the head of project well understands the code written by the other project members. Each line of the code must be well documented. 

#### What are your milestones?
Depends on the team size.  However, roughly speaking:
- Milestone 1 : List of features (regarding version 1) and marketing strategy/promotion targeting industry - January 15th 2021
- Milestone 2 : Wireframe February 1st 2021
- Milestone 3 : REST API + Front-end UI (if done simultaneously) in alpha by March 20th 2021
- Milestone 4 : Beta April 3rd 2021
- Milestone 5: to be continued...

The motivation of the other members may strongly influence the project development speed. If it is a one person project, it is hard to evaluate the deadlines. 

#### Tell us about your team members:
Team not defined yet.

Head of project:
Name: Nenad Savic
Skilled in: Research, exposure sciences, chemistry, statistics, Django/Python, REST API, JavaScript, React, R, Linux...
Github: https://github.com/sawicnenad
Linkedin: https://www.linkedin.com/in/nenad-savic-phd/
Slack ID: U01GRD6V1KQ

#### List the roles of any additional team members you would be looking for?
1 x Full stack web developer (Django REST API/React) or 1xDjango + 1xReact developer
(to be defined)

**Comment by manishram** [comment]
Hey @sawicnenad , I really liked your project proposal. Infact, one of the best Project-Proposals I've gone through. Next you have to comment down here your github repository url of the project. You can provide empty repository url as well if you have not already started working on the project.

**Comment by sawicnenad** [comment]
Thanks for the quick feedback! No worries, I do it today.

**Comment by sawicnenad** [comment]
> Hey @sawicnenad , I really liked your project proposal. Infact, one of the best Project-Proposals I've gone through. Next you have to comment down here your github repository url of the project. You can provide empty repository url as well if you have not already started working on the project.

**Comment by sawicnenad** [comment]
https://github.com/sawicnenad/O3one

**Comment by manishram** [comment]
Hey, @sawicnenad your project has been added to the repository.
**O3one**: https://github.com/thenewboston-developers/Project-Proposals/tree/master/projects/28-O3one
