### ISSUE TITLE
(Draft) MaakayBot - Multi Server Support + Fees - 2

### ISSUE THREAD

**Issue by hussu010** [thenewboston-developers/Project-Proposals#287]
#### Link to original project proposal.
https://github.com/thenewboston-developers/Projects/issues/278

#### Link to most recent milestone payout request.
To be added

#### Milestone Description
In this milestone, we will be expanding the bot to support multiple servers as well as introducing the fees to provide initiative for discord server owners. The server owners can invite the bot into their server, let their audience use it, and the fees will get into their pocket (is not it noice?).
The fees will be charged if someone uses the `tip` (1 TNBC), `challenge` (1 TNBC), or `tournament` (X%) command.  

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 | Design the bot to support multiple servers | Invite bot into multiple discord servers |
| 2 | Admin and Manager roles for each server | The roles will be created automatically after the invitation of bot |
| 3 | `/admin set_withdrawal_address address: ADDRESS`: Lets the server admin set withdrawal address | Use the command |
| 4 | `/admin withdraw amount: AMOUNT`: Lets the server admin withdraw fee reward | Use the command |
| 5 | `/user transactions`: Let the user view transaction history | Use the command |
| 6 | `/tip history`: Lets user view the tip history | Use the command |
| 7 | Implement the fee such that its 80/20 shared with the server owner and the bot owner | Check the fees collected |
| 8 | Prompt the user if they want to accept the challenge and only start if they accepted | Use challenge command |
| 9 | Prompt the referee if they want to referee the challenge | Use the challenge command |
| 10 | Enforce permission on challenge acceptance | Accept or reject a challenge by unauthorized user |
| 11 | Enforce beta decimals | All the balances will be in decimals |
| 12 | Don't let the user withdraw non-decimal tnbc | Try the commands with decimals |
| 13 | `/admin set_tournament_channel` | Sets the tournament channel for the server |

#### How long do you estimate this milestone will take to complete?
12 days

#### Project Wallet
PROJECT WALLET ACCOUNT NUMBER HERE

**Comment by tspearing** [comment]
@hussu010, there's no need for a milestone as we approved the MVP in the original proposal. Once that's done, if needed, additional milestones can be added.
