### ISSUE TITLE
TNBPAY - Feature update

### ISSUE THREAD

**Issue by olowudaniel1** [thenewboston-developers/Project-Proposals#288]
#### Link to original project proposal.
#172 

#### Link to most recent milestone payout request.
#263 

#### Milestone Description
A feature update to the WooCommerce Plugin. Addition of Shortcodes, making it possible for store owners to add the TNBPAY button anywhere on their website and receive payment.

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
Adding shortcodes so the payment button can be used anywhere on the website
Adding parameters to shortcodes
Making the button a means of form validator also, so store owners can collect form inputs on successful payment
Updating the doc, so users can understand how to us this feature as it is a little technical

#### How long do you estimate this milestone will take to complete?
7 days

#### Project Wallet
86ee75d4cea77ca8339cc97f5e7426a3434d9f91465cd441c0c7593bd852e955

**Comment by tspearing** [comment]
Approved.
