### ISSUE TITLE
TNBPay - Feature update 

### ISSUE THREAD

**Issue by olowudaniel1** [thenewboston-developers/Project-Proposals#290]
#### Link to the milestone and objectives table.
#288 

#### Detailed log of all completed objectives including valid proof of work.
The github repo has been updated. Doc also has been updated. https://github.com/akandejaphet/TNBPay

It can be tested live here > https://tnbcgames.com/enroll/

#### Project Wallet
86ee75d4cea77ca8339cc97f5e7426a3434d9f91465cd441c0c7593bd852e955

**Comment by tspearing** [comment]
@olowudaniel1 , some points:

- "Your enrollment was successful, the bracket would be updated soon." Should be "Your enrollment was successful, the bracket will be updated soon."

- The countries are not in order. Do we need countries? Some people may not want to reveal this.

- I hit "Payment made, next" after not sending the payment and it still said it was successful.

**Comment by olowudaniel1** [comment]
Fixed

**Comment by tspearing** [comment]
Approved.

**Comment by manishram** [comment]
Approved for 10000 TNBC.
