### ISSUE TITLE
TNB Gifts - Front-End and Hosting - MILESTONE_2

### ISSUE THREAD

**Issue by picko1990** [thenewboston-developers/Project-Proposals#291]
#### Link to original project proposal.
https://github.com/thenewboston-developers/Projects/issues/201

#### Link to most recent milestone payout request.
https://github.com/thenewboston-developers/Projects/issues/289

#### Milestone Description
Front End development and hosting

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 | Front-End and Hosting | They can access and check it online |

#### How long do you estimate this milestone will take to complete?
2 weeks

#### Project Wallet
b0b0b98f9bd0b9809ac30706363ccfe7294fc5dc06eec9fb916bb17e8d91536e

**Comment by tspearing** [comment]
Approved
