### ISSUE TITLE
TNBPAY- Feature Update (02)

### ISSUE THREAD

**Issue by olowudaniel1** [thenewboston-developers/Project-Proposals#292]
#### Link to original project proposal.
#172 

#### Link to most recent milestone payout request.
#290 

#### Milestone Description
Check for confirmations before validating the transactions 

#### How long do you estimate this milestone will take to complete?
5 days

#### Project Wallet
86ee75d4cea77ca8339cc97f5e7426a3434d9f91465cd441c0c7593bd852e955

**Comment by tspearing** [comment]
Approved.
