### ISSUE TITLE
TNBC Game Jam

### ISSUE THREAD

**Issue by wakawakathedev** [thenewboston-developers/Project-Proposals#293]
# Project Details

#### How would you describe your project?
This project is an online game jam. 

Game jams (e.g. Ludem Dare/itch.io/GGJ) are short events held over 48-72 hours where people collaborate in teams to create a game. This project would serve as a guide for others in future on running their own game jam.
Teams are asked to submit their game at the end of the event, where the games are then judged by the community, 
based on criteria such as aesthetics, playability and game design. 
The top games are then selected for official judges to award the winners with prizes and recognition at the end of the event.

My role as planner/organiser would be to facilitate the jam 
(as well as ensure there's an agenda for the event rundown).

Apart from this, I would also look to participate as a team member but recluse myself from any prizes. 

#### What problem does this project solve?
This project aims to provide an opportunity programmers/non-programmers to create games within thenewboston community.

#### Who is the target market?
thenewboston community + game designers (artists/programmers)

#### How will this project benefit the network and/or the community?
Since the recently announcement that thenewboston aims to go into the gamedev community, it makes sense to host a game jam.

#### How is this project centered around thenewboston?
Given that thenewboston has a core goal to tap into the gamedev community, it makes sense that one of goals of the event would be to provide integrations using thenewboston SDKs. (e.g. Challenge 1: Use TNBC within your game)

#### What is the estimated completion date for this project? (rough estimates are acceptable)
Planning Dec 2021/Jan 2022

#### What is your Discord username?
wakawaka #9513 (https://discord.gg/thenewboston)

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)

| # | Milestone             | Description                            | Verification Method |
| - | --------------------- | -------------------------------------- | --- |
| 1 | Planning for event    | Create Game jam guide + Planning doc   | Notion |
| 2 | Online signup form    | Notion[doc] + link                     | Notion + website |
| 3 | Operations            | During the event, how can ppl collab with each other? | Guide + Discord Server/Thread | 
| 4 | After Event           | Judging method (include in step 1)     | Discord Party |

# Milestone 1 - Minimum Viable Product (MVP) Details

---

#### MVP Description
- Game Jam Planning, A transparent how-to guide on planning and running a game jam with thenewboston community. 

#### Objectives for MVP

| # | Objective                          | How can auditors verify milestone?     |
| - | ---------------------              | -------------------------------------- |
| 1 | Game Jam Planning                  | Notion |
| 2 | Get Preliminary Judges             | Notion |
| 3 | Game Jam guide: How to Participate | Notion |
| 4 | Marketing Guide                    | Notion |

#### How long do you estimate for the MVP to complete?
2-3 weeks.

#### Project Wallet
`920a01fd478d7bfbf850003af8bf2c404cf041d639091aa8413de50fb5d1f238`

**Comment by tspearing** [comment]
@wakawakathedev, does this idea need a separate website, or could it be run through discord? The core team already talked about a hackathon a few months ago.

**Comment by wakawakathedev** [comment]
I would say a website can help with marketing/information (however, i wouldn't place a lot of resources for developing that).

Being pragmatic, including that information on a notion site may just be sufficient and later, if we see more hackathons/jams in the future, I'd say we can migrate the content onto a site + get a paid domain.

for MVP, I dont think its entirely necessary at the moment

**Comment by tspearing** [comment]
Closing as we've discussed and the marketing team will contact @wakawakathedev if they are needed when there is a hackathon in the future.
