### ISSUE TITLE
Keysign Mobile - Whole app - 1

### ISSUE THREAD

**Issue by mrbusysky** [thenewboston-developers/Project-Proposals#294]
#### Link to the milestone and objectives table.
https://docs.google.com/document/d/1Oc4MfOutaAE7E5TqndLtpUftGcYtYeN1x7hGgn3nMWU/edit#heading=h.l4w0crdwla0x

#### Detailed log of all completed objectives including valid proof of work.
Everything in those documents has been completed. 
The list is way too long for me to put in this document.

#### Proof of work:
* App working: https://www.youtube.com/watch?v=e2WI2ZgB7Ks
* Transfer working: https://www.youtube.com/watch?v=wIZM4Ckj-Os
* Verify handshake: https://www.youtube.com/watch?v=tO7SlneKzCM
* Transfer handshake: https://www.youtube.com/watch?v=CRYFWg9IUOE

#### Extra notes:
Manish, Justin, bucky, and so on have been sent the apk to be able to test the code.
Manish has access to the code.

#### Project Wallet
fe06754d2dbf23509e975809e9023b620509c1e6618472f16c9659f59e940337

**Comment by manishram** [comment]
Approved for 750K with the addition of the Friends' feature.

**Comment by mrbusysky** [comment]
Okay deal

**Comment by mrbusysky** [comment]
All things in the project are completed including the addition to the friend's system.
