### ISSUE TITLE
Maakay Discord Bot - MVP - 1

### ISSUE THREAD

**Issue by hussu010** [thenewboston-developers/Project-Proposals#295]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/278

#### Detailed log of all completed objectives including valid proof of work.

| # | Objective             | How can auditors verify milestones?     |
| - | --------------------- | -------------------------------------- |
| 1 | Set up discord bot and host in test discord server | https://discord.gg/SyCg3Cgw |
| 2 | Deposit TNBC into bot account | Use `/deposit tnbc` command  |
| 3 | Balance check | Use `/balance` command to check the current withdrawal address, available and locked balance |
| 4 | Set/ Update Withdrawl Address | Use `/set_withdrawl_address tnbc` to set/ update withdrawal address |
| 5 | Withdraw TNBC from bot account | Use `/withdraw tnbc <amount>` command |
| 6 | Check user profile | Use `/profile <user (optional)>` command |
| 7 | Tip Feature | Use `/tip tnbc <user> <amount> <message>` command and check the balance of both sender and recipient |
| 8 | Start Challenge between users | Use `/challenge new <title> <amount> <contender> <referee>` command |
| 9 | Reward the winner of challenge | Challenge referee can use `/challenge reward <challenge_id> <winner>` command to reward the winner |
| 10 | Start Tournament | Use `/tournament new <title> <description> <amount> <url (optional)>` command |
| 11 | Only allow the members with a specific role to host the tournament  | We decided to let everyone host tournament but there's minimum amount set |
| 12 | Reward the winner of tournament | the host can use `/tournament reward <tournament_id> <winner>` command to reward the winner |
| 13 | Show tournament start/ end notification on separate channel | Check the #tournament channel  |
| 14 | Check the challenge list | Use `//challenge all` to list all the active challenges of the user  |
| 15 | Implement the bot with database | Check the code base |

#### Project Wallet
79c0d308e31b9c4cf0f2bdaae65e2d8476c355084035ee11755facaa9597ff98

**Comment by tspearing** [comment]
@hussu010, we tried to test, but every command returned "This interaction failed".

**Comment by hussu010** [comment]
@tspearing it is because I'll need to run the dev instance running in the local machine. So before testing, I recommend to let me know so that I can spin up the server.

Thanks.

**Comment by manishram** [comment]
Approved for 60 000 TNBC
