### ISSUE TITLE
Formalizing QR Standards

### ISSUE THREAD

**Issue by mrbusysky** [thenewboston-developers/Project-Proposals#296]
# Project Details

#### How would you describe your project?
This format is something other projects should follow some all apps can connect to each other easily via payments, syncing wallets, and so on.

#### What problem does this project solve?
A universal standard that allows apps to interact easily.

#### Who is the target market?
Everyone
#### How will this project benefit the network and/or the community?
States above

#### How is this project centered around thenewboston?
Of course

#### What is the estimated completion date for this project? (rough estimates are acceptable)
This depends on how the main team wants to deal with this. Since they would likely want a PR for the main website for the developer portal as discussions had with Justin K.

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
Write standard for QR codes and how the store data for certain transactions.

#### What is your Discord username?
MrSky#5242

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)
I was told not to worry about the FE so I'll only be including a document.

---

#### MVP Description
Detailed document of the standard

#### Objectives for MVP

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 | Full QR standard write up | https://docs.google.com/document/d/1rwjkrsnSl0fIuVHpxv8rOHMoO1m8scofqGLtlm0dLsY/edit |

#### How long do you estimate for the MVP to complete?
A couple of days at most
#### Project Wallet
fe06754d2dbf23509e975809e9023b620509c1e6618472f16c9659f59e940337

**Comment by mrbusysky** [comment]
This is completed and paid

**Comment by wakawakathedev** [comment]
@manishram / @tspearing - Think we may wish to improve upon this process by tagging this Project as a Request-For-Comment (and perhaps have different stages for Community/App Standards) going forward. This feels important that, if we're implementing something for the community, that there can be an opportunity for openness and discourse on how RFCs can improve the app development process.

Initial Draft for RFC stages: - 

Inspired by [EcmaScript](https://nitayneeman.com/posts/introducing-all-stages-of-the-tc39-process-in-ecmascript/) / [Rundown](https://tc39.es/process-document/)

- [ ] Stage 0: Initial Idea
- [ ] Stage 1: Proposal (RFC stage - should be time boxed + discord channel announcement to interested parties)
- [ ] Stage 2: Draft 
- [ ] Stage 3: Candidate
- [ ] Stage 4: Final

---

[NPM](https://github.com/npm/rfcs/issues) uses a somewhat different model, but that could also be considered, Happy to recieve feedback on this as well if others have alternative frameworks to base this on.

Tagging the following developers that may be interested in this conversation.
cc: @Kycermann @itsnikhil @hussu010 @led76marx @thesanjeevsharma

**Comment by tspearing** [comment]
@wakawakathedev, why don't we discuss this in an audit meeting next week? I think this is bigger than just the three of us and we could invite others to participate.

**Comment by wakawakathedev** [comment]
Sounds good.

Feel free to send me a Google hangout invite.
