### ISSUE TITLE
TNBC Analytics - Frontend and Backend development - 02

### ISSUE THREAD

**Issue by SazidAhmed** [thenewboston-developers/Project-Proposals#297]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/270

#### Detailed log of all completed objectives including valid proof of work.

We've completed the frontend and backend development of TNBC Analytics following the MVP design and architecture.

Proof of Works : 

1. Frontend Development | 

Hosted staging web app : https://tnbc-analytics.netlify.app/

Frontend Source Codes : https://github.com/Techminate/TNBC-Analytics-Frontend

2. Backend Development | 

Swagger API documentation : https://tnbanalytics.pythonanywhere.com/swagger/
Backend server : https://tnbanalytics.pythonanywhere.com
Admin portal : https://tnbanalytics.pythonanywhere.com/admin/
Admin Login Credentials :-
Username: tnbanalytics
Password: Dev@server.analytics

Backend Source Codes : https://github.com/Techminate/TNBC-Analytics-Backend

## Project Wallet
a5dbcded3501291743e0cb4c6a186afa2c87a54f4a876c620dbd68385cba80d0

**Comment by tspearing** [comment]
Approved. Paying 70 000 TNBC based on the work delivered.
