### ISSUE TITLE
Formalizing QR Standards - Full document scope - Milestone 1

### ISSUE THREAD

**Issue by mrbusysky** [thenewboston-developers/Project-Proposals#298]
#### Link to original project proposal.
https://github.com/thenewboston-developers/Projects/issues/296

#### Link to most recent milestone payout request.
N/A

#### Milestone Description
SHORT DESCRIPTION OF MILESTONE HERE

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 | Document for QR data and scan methods | https://docs.google.com/document/d/1rwjkrsnSl0fIuVHpxv8rOHMoO1m8scofqGLtlm0dLsY/edit |

#### How long do you estimate this milestone will take to complete?
A couple of days

#### Project Wallet
fe06754d2dbf23509e975809e9023b620509c1e6618472f16c9659f59e940337

**Comment by manishram** [comment]
Approved for 1000 TNBC
