### ISSUE TITLE
TNBC Games - Milestone 2

### ISSUE THREAD

**Issue by olowudaniel1** [thenewboston-developers/Project-Proposals#299]
#### Link to the milestone and objectives table.
#279 

#### Detailed log of all completed objectives including valid proof of work.
Hi-fi design that contains all basic pages, more pages to be designed as project progresses.
https://www.figma.com/file/QIzaXTvRGf31z6qgEHSrVf/TNBC-Games?node-id=0%3A1

#### Project Wallet
86ee75d4cea77ca8339cc97f5e7426a3434d9f91465cd441c0c7593bd852e955

**Comment by tspearing** [comment]
Approved for 50k TNBC.
