### ISSUE TITLE
TNBPAY- Feature update (02)

### ISSUE THREAD

**Issue by olowudaniel1** [thenewboston-developers/Project-Proposals#300]
#### Link to the milestone and objectives table.
#292 

#### Detailed log of all completed objectives including valid proof of work.
https://github.com/akandejaphet/TNBPay

#### Project Wallet
86ee75d4cea77ca8339cc97f5e7426a3434d9f91465cd441c0c7593bd852e955

**Comment by tspearing** [comment]
Approved for 2k TNBC.
