### ISSUE TITLE
Formalizing QR Standards - Full document scope - Milestone 1

### ISSUE THREAD

**Issue by mrbusysky** [thenewboston-developers/Project-Proposals#302]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/298

#### Detailed log of all completed objectives including valid proof of work.
Fully document complete

#### Project Wallet
fe06754d2dbf23509e975809e9023b620509c1e6618472f16c9659f59e940337

**Comment by tspearing** [comment]
Paid 1000 TNBC.
