### ISSUE TITLE
Discord Python Payment Framework

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Project-Proposals#303]
# Project Details

#### How would you describe your project?
Payment framework so that Discord Python app developers can easily accept coin payments for their app.

#### What problem does this project solve?
It is currently difficult for Discord Python developers to accept coins as payments. This is because thenewboston blockchain technology is new and there aren't many existing resources (videos, documentation, tutorials, guides, etc...) to show people how to integrate it into their Discord apps.

This project solves those problems by not only providing a complete open source integration framework to make it easy for developers to accept coins, but also a series of tutorial reviewing the overall architecture and teaching developers exactly how to use it.

#### Who is the target market?
All Discord Python developers.

#### How will this project benefit the network and/or the community?
It will provide Discord developers a way to easily accept coin payments for their Discord apps. This can be used for purchasing in game items, game collectables, bots where people can list items for fees, bots that charge for a service, and many more use cases.

#### How is this project centered around thenewboston?
It was built from the ground up with the goal of making it easy for Discord developers to be able to integrate with thenewboston blockchain.

#### What is the estimated completion date for this project? (rough estimates are acceptable)
Already completed.

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
n/a (will wait for user feedback to see which additional features should be built)

#### What is your Discord username?
Bucky#2734

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)

![Register](https://user-images.githubusercontent.com/8547538/135932214-eaaf04a3-fad0-4a98-877f-b555149b5dd1.png)

![Verify](https://user-images.githubusercontent.com/8547538/135932215-33a1e6a8-1d8b-4547-b1db-e98510da4566.png)

![Deposits](https://user-images.githubusercontent.com/8547538/135932212-948b2b1c-2d87-480f-9dd0-eebeffe280e1.png)

# Milestone 1 - Minimum Viable Product (MVP) Details

Please include a detailed breakdown of the MVP including a list of all quantifiable objectives. Upon 
completion of the MVP, each objective will be reviewed by thenewboston team and once all objectives have been 
verified as completed, amount of coins will be negotiated. 

Note that all future detailed milestone breakdowns will be written as a separate GitHub issue. Only the first 
milestone which is for MVP is included in this project proposal.

---

#### MVP Description
MVP includes the basic registration, verification, and blockchain integration.

#### Objectives for MVP

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 | Register account number | Register command to link TNB account number with Discord user |
| 2 | Update account number | Once registered, auditors can use the register command again to re-register an updated account number |
| 3 | Send/receive payments | Once registered, users can send coins to the bot and auditors can verify the users balance increases |

#### How long do you estimate for the MVP to complete?
Already completed

#### Project Wallet
a37e2836805975f334108b55523634c995bd2a4db610062f404510617e83126f

**Comment by tspearing** [comment]
Approved. Please create a milestone payout request.
