### ISSUE TITLE
Discord Python Payment Framework - Registration, verification, and blockchain integration - 1

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Project-Proposals#304]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/303

#### Detailed log of all completed objectives including valid proof of work.
- https://github.com/buckyroberts/Discord-Python-Framework
- https://www.youtube.com/watch?v=2AYNHncLjgw
- https://www.youtube.com/watch?v=heTj_a0Ghb4
- https://www.youtube.com/watch?v=9vqA2OBREOA
- https://www.youtube.com/watch?v=BQJiUj12PvY

#### Project Wallet
a37e2836805975f334108b55523634c995bd2a4db610062f404510617e83126f

**Comment by tspearing** [comment]
Approved for 50k TNBC.
