### ISSUE TITLE
TNBC Analytics - Testing and Deployment - 03

### ISSUE THREAD

**Issue by SazidAhmed** [thenewboston-developers/Project-Proposals#306]
#### Link to original project proposal.
https://github.com/thenewboston-developers/Projects/issues/255

#### Link to most recent milestone payout request.
https://github.com/thenewboston-developers/Projects/issues/297

#### Milestone Description
We've already hosted the development version of "TNBC Analytics" as a proof of work of milestone 2.
Links : 
Frontend : https://tnbc-analytics.netlify.app/
Backend : https://tnbanalytics.pythonanywhere.com

In this milestone we'll make it production ready. The tasks we're going to do are given below:

1. Code optimization for better performance on both backend and frontend
2. fixing the bugs available in govt and treasury statistics.
3. Improvement of graphs
4. add appropriate contents on the FAQs page 
5. add search functionalities in the data tables.
6. add a one click redirection to github issue from table data
7. Buy a domain name as "tnbcanalytics.com" and host the production ready "TNBC Analytics".

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 | Production build & deployment | Production ready application would be provided with completing all of the above tasks |

#### How long do you estimate this milestone will take to complete?
3 weeks

#### Project Wallet
a5dbcded3501291743e0cb4c6a186afa2c87a54f4a876c620dbd68385cba80d0

**Comment by tspearing** [comment]
Approved.
