### ISSUE TITLE
Decentralized digital voting application  - NAME_OF_MILESTONE - MILESTONE_NUMBER

### ISSUE THREAD

**Issue by Tinsae12219** [thenewboston-developers/Project-Proposals#308]
#### Link to the milestone and objectives table.
ADD LINK HERE

#### Detailed log of all completed objectives including valid proof of work.
LINK TO ACCEPTABLE PROOF OF WORK DOCUMENT HERE

#### Project Wallet
PROJECT WALLET ACCOUNT NUMBER HERE

**Comment by manishram** [comment]
Feel free to reopen this issue when the milestone is ready for review.
