### ISSUE TITLE
TNBGem - All about accounts- 1

### ISSUE THREAD

**Issue by avinashupadhya99** [thenewboston-developers/Project-Proposals#309]
#### Link to the milestone and objectives table.
[Project proposal here](https://github.com/thenewboston-developers/Projects/issues/245)

#### Detailed log of all completed objectives including valid proof of work.

Repo url - https://github.com/avinashupadhya99/TNBGem

| # | Objective | How can auditors verify milestone? |
| - | --------------------- | -------------------------------------- |
| 1 | createAccount | Check [code in Github](https://github.com/avinashupadhya99/TNBGem/blob/39ac88e72aa084a605784e858d502edd0536f45f/lib/thenewboston/account.rb#L9) and verify using the network |
| 2 | createSignature| Check [code in Github](https://github.com/avinashupadhya99/TNBGem/blob/39ac88e72aa084a605784e858d502edd0536f45f/lib/thenewboston/account.rb#L23) and verify using the network |
| 3 | verifySignature | Check [code in Github](https://github.com/avinashupadhya99/TNBGem/blob/39ac88e72aa084a605784e858d502edd0536f45f/lib/thenewboston/account.rb#L44) and verify using the network |
| 3 | verifyKeyPair | Check [code in Github](https://github.com/avinashupadhya99/TNBGem/blob/39ac88e72aa084a605784e858d502edd0536f45f/lib/thenewboston/account.rb#L38) and verify using the network |
| 4 | Tests | [Run the test command](https://github.com/avinashupadhya99/TNBGem/runs/3828266395?check_suite_focus=true#step:4:49) in the [repo](https://github.com/avinashupadhya99/TNBGem/blob/main/test/account_test.rb) and see if it passes |
| 5 | Documentation | Read the [docs](https://avinashupadhya99.github.io/TNBGem/) |

#### Project Wallet
94cf53921e9c5ddf48dc5589b7cdf111f7acdc93dc3073b94880416d4676b9ae

**Comment by manishram** [comment]
Approved for 15000 TNBC.
