### ISSUE TITLE
PAY TNB

### ISSUE THREAD

**Issue by olowudaniel1** [thenewboston-developers/Project-Proposals#312]
# Project Details

#### How would you describe your project?
A payment link generator.  It will be a website where users input their account number and amount they want to receive. A payment link is generated. They share the link to whoever they want to. Whoever visits the link has the option to either pay via scanning QR code or using other payment options. T

#### What problem does this project solve?
It solves the problem of having to send your account number to everyone especially when it is for donations.

#### Who is the target market?
Everyone that uses TNB

#### How will this project benefit the network and/or the community?
Everyone in the community can make use of the project

#### How is this project centered around thenewboston?
TNB is our only currency

#### What is the estimated completion date for this project? (rough estimates are acceptable)
4 weeks

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
It is pretty straight forward. We will developing the site at once.

#### What is your Discord username?
Weird Guy#6773

# Milestone 1 - Minimum Viable Product (MVP) Details

We will be building the complete product at once that contains all functionalities.
---

#### Project Wallet
86ee75d4cea77ca8339cc97f5e7426a3434d9f91465cd441c0c7593bd852e955

**Comment by hussu010** [comment]
tnbexplorer has this feature integrated already: https://tnbexplorer.com/tnb/payment-request?recipient=fe06754d2dbf23509e975809e9023b620509c1e6618472f16c9659f59e940337&amount=1&memo=Payment%20Request%20via%20TNB%20Explorer

**Comment by olowudaniel1** [comment]
Hey @hussu010, I checked out the link, it is quite difference from the proposed project

**Comment by hussu010** [comment]
Hi, @olowudaniel1 it's the same. All it lacks is a QR code. 
So if I want to request 10k TNBC from you, I'll send https://tnbexplorer.com/tnb/payment-request?recipient=22d0f0047b572a6acb6615f7aae646b0b96ddc58bfd54ed2775f885baeba3d6a&amount=10000&memo=I%20need%20those%20TNBC., and you can visit the site directly and pay via Keysign.

**Comment by hussu010** [comment]
And tnbexplorer also supports Bulk payments (using Keysign), so you can request multiple payments at once.

To be clear, I'm not opposing the idea. But it'd be wise to use the tnbexplorer for requesting payments since you'd not want to visit another site (www.xyz.com) just for requesting payments.

**Comment by olowudaniel1** [comment]
Does tnbexplorer supports only Keysign for payment?

**Comment by olowudaniel1** [comment]
Having a direct site for payment link is preferable as it is quick and easier, however, I will leave for that the Auditors to decide. 

Here are a few difference in the proposed project. Users input account number and amount only. Amount will be optional as we want this to be multipurpose. If users do not input amount, the receiving user input the amount he want to pay in and proceed with payment, this is very good for donation, giving the receiving user the choice to donate whatever amount they please. Memos are automatically generated by the system and it will support QR code and other payment options that will come with beta. Payment links generated are short and dynamic.

Here is a similar example https://paynano.me/

**Comment by mrbusysky** [comment]
There is already a donation website project that is doing this and also tnbexplorer has it as well.

**Comment by olowudaniel1** [comment]
Thanks @mrbusysky and @hussu010 for the heads up.

**Comment by tspearing** [comment]
@olowudaniel1 decided to work with the TNBC explorer team instead of making a new project.
