### ISSUE TITLE
thenewboston Blockchain Video Tutorials - First 5 videos in the series - 1

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Project-Proposals#315]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/313

#### Detailed log of all completed objectives including valid proof of work.
- https://www.youtube.com/watch?v=O6PxPvtlFAo
- https://www.youtube.com/watch?v=40Wv6T91dm0
- https://www.youtube.com/watch?v=xErZtod1eys
- https://www.youtube.com/watch?v=jS9uNcYwLAU
- https://www.youtube.com/watch?v=mQpBT_q19QM

#### Project Wallet
a37e2836805975f334108b55523634c995bd2a4db610062f404510617e83126f

**Comment by manishram** [comment]
Approved for 50000 TNBC
