### ISSUE TITLE
Maakay Discord Bot - Furnish and Release - 2

### ISSUE THREAD

**Issue by hussu010** [thenewboston-developers/Project-Proposals#318]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/305

#### Detailed log of all completed objectives including valid proof of work.

| # | Objective             | How can auditors verify milestones?     |
| - | --------------------- | -------------------------------------- |
| 1 | `/transactions tnbc`: Let the user view transaction history | Use the command |
| 2 | `/tip history`: Lets user view the tip history | Use the command |
| 3 | Prompt the user if they want to accept the challenge and only start if they accepted | Use the challenge command |
| 4 | Prompt the referee if they want to referee the challenge | Use the challenge command |
| 5 | Enforce permission on challenge acceptance | Accept or reject a challenge by unauthorized user |
| 6 | Enforce beta decimals | All the balances will be in decimals |
| 7 | Don't let the user withdraw non-decimal TNBC | Try the commands with decimals |
| 8 | Launch the bot on TNB Gaming discord server | Check thenewboston gaming discord server |
| 9 | Reiterate all instances of `/tournament` to `/host challenge` | Use the commands |
| 10 | Run series of QA tests | There should be no bugs when the demo is presented |
| 11 | Implement `/challenge cancel` command | Use the command |
| 12 | Write guides on the bot usage | https://github.com/maakay-com/maakay-discord-bot#readme |
| 13 | Gif demo on the usage of different commands of the bot | `/help gifs <command>` and GIF are available on README.md |
| 14 | Separate out `/help` commands into category | There will be different categories of help command |
| 15 | Continuous deployment of features to the production | The features will be pushed into the production bot continuously |
| 16 | Implement discord Cogs across the bot to build the source code cleaner | Check the source code |

Logo
![Center-alt3-discord](https://user-images.githubusercontent.com/55182298/139005759-20117073-eeb1-4e76-851b-1958136a0414.png)

#### Project Wallet
79c0d308e31b9c4cf0f2bdaae65e2d8476c355084035ee11755facaa9597ff98

**Comment by tspearing** [comment]
@hussu010, please update the discord server for Maakay with the latest code base. We aren't able to use the new commands.

**Comment by hussu010** [comment]
Hi @tspearing, the command guides are available here: https://github.com/maakay-com/maakay-discord-bot#commands

Just edited `/user transactions` to `/transactions tnbc`

regards.

**Comment by manishram** [comment]
Approved for 40k TNBC.
