### ISSUE TITLE
TNBC-Contributors - MVP - 1

### ISSUE THREAD

**Issue by hussu010** [thenewboston-developers/Project-Proposals#320]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/319

#### Detailed log of all completed objectives including valid proof of work.
| # | Objective             | How can auditors verify milestones?     |
| - | --------------------- | -------------------------------------- |
| 1 | Create a repo with contributors info and new signature addition workflow | https://github.com/tnbCrow/TNBC-Contributors |

#### Project Wallet
79c0d308e31b9c4cf0f2bdaae65e2d8476c355084035ee11755facaa9597ff98

**Comment by tspearing** [comment]
Approved for 1000 TNBC.
