### ISSUE TITLE
TNBC Mobile Wallet - MVP Feature set - 1

### ISSUE THREAD

**Issue by wakawakathedev** [thenewboston-developers/Project-Proposals#325]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/324

#### Detailed log of all completed objectives including valid proof of work.
https://github.com/wakawakathedev/tnbc_mobile_template/pull/1

#### Project Wallet
`2ecd5ebdfff0ace53bb0f171645f912593b2c9eda722548831a4b32221245525`

**Comment by wakawakathedev** [comment]
@manishram any update on this?

**Comment by tspearing** [comment]
@wakawakathedev we are reviewing the code and will get back to you. It will take longer than a normal project so could be up to two weeks.

**Comment by manishram** [comment]
Approved for 200K TNBC.
