### ISSUE TITLE
TNB Ecosystem BOT - Milestone #1

### ISSUE THREAD

**Issue by probablyArth** [thenewboston-developers/Project-Proposals#331]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/321

#### Detailed log of all completed objectives including valid proof of work.
https://github.com/ArthThapa/TNB-Ecosystem-Bot

#### Project Wallet
51607a626a2a7a326ed532162a32addedb0fe85b6ffddb1846e10cc778fd9a3d

**Comment by probablyArth** [comment]
Guys It's been two weeks, any update?

**Comment by Kycermann** [comment]
Approved for 15k.
