### ISSUE TITLE
Automated Freelancing Service - 1 - 1

### ISSUE THREAD

**Issue by Kycermann** [thenewboston-developers/Project-Proposals#332]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/178

#### Detailed log of all completed objectives including valid proof of work.
**Discord link**: https://discord.gg/E6q48kKeVC
**Link to code**: https://github.com/Kycermann/tnb-freelance

| # | Objective           |  Evidence  |
| - | ------------------- | ------------------------- |
| 1 | Set up Discord server | https://discord.gg/E6q48kKeVC |
| 2 | Terms & Conditions | In Discord #terms-of-service |
| 3 | Freelancer agreement & recruit 10+ freelancers | In Discord / #terms-of-service |
| 4 | Set up Discord bot code | Bot is online in Discord |
| 5 | /ticket | Try it |
| 6 | Claim a ticket (button) | Try it as a freelancer |
| 7 | /invoice <amount> | Try it as a freelancer |
| 8 | Sending / receiving TNBC | Invoices will be marked as paid, coins are sent on /close |
| 9 | /set_address <address> | Try it and make an invoice |
| 10 | /close release and /close refund | Try it |

#### Project Wallet
f1decb80339a4bb6c089b77cbac553e23a6ca86b0cfc64adb8c8eb8f8b57d815

**Comment by manishram** [comment]
Approved for 50k TNBC.
