### ISSUE TITLE
Create TNB App

### ISSUE THREAD

**Issue by Kycermann** [thenewboston-developers/Project-Proposals#333]
# Project Details

#### How would you describe your project?

Build apps on client based contracts without writing the same boilerplate code for each project. The state of your app will be calculated from the TNB transaction history at your app's TNB address. Inspired by Create React App.

1. Run `create-tnb-app <name>`
2. Boom. You've got a full TNB app template with structure and APIs

#### What problem does this project solve?

Use cases:

- On chain domains
- On chain real time games (in Beta)
- On chain collectible games
- On chain private messaging
- Full on chain social network
- NFTs

Real projects already using these APIs:
- TNB Discord Shop
- TNB Freelance
- TNB Heroes

#### Who is the target market?
Developers.

#### How will this project benefit the network and/or the community?
Project template and reusable code / APIs for other projects.

#### How is this project centered around thenewboston?
1. Run `create-tnb-app <name>`
2. Boom. You've got a full TNB app template with good structure and powerful APIs

#### What is the estimated completion date for this project? (rough estimates are acceptable)
4 weeks from approval

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
1. Optimise, test, tweak and release the above APIs to npm
2. Create a project template using the APIs and the `create-tnb-app` command

#### What is your Discord username?
Pixel#5000

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… 

_WIP APIs (to be finalised):_

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/59399685/139747899-a47e29e0-7548-4673-9ca2-5c3c2e7650e6.png">

<img width="1091" alt="Screenshot 2021-11-01 at 22 02 08" src="https://user-images.githubusercontent.com/59399685/139747933-7d24e77b-973a-444f-860e-c817b48b1840.png">

<img width="1097" alt="Screenshot 2021-11-01 at 22 02 30" src="https://user-images.githubusercontent.com/59399685/139747963-6ca1a01f-34d0-4f35-b083-e0bdcc3685ec.png"><img width="1095" alt="Screenshot 2021-11-01 at 22 02 43" src="https://user-images.githubusercontent.com/59399685/139747981-160f3943-b833-446e-9447-72040da38ce0.png">

# Milestone 1 - Underlying APIs

---

#### MVP Description
Basic APIs.

#### Objectives for MVP

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 | Code a compact chain memo reader/writer | Check out the API, documentation and run the tests |
| 1.1 | Code | See the code |
| 1.2 | Extensive tests | See the tests & run them |
| 1.3 | Extensive docs | Read the docs |
| 2 | Memo reader/writer to convert Javascript objects directly to/from memos | Check out the API, documentation and run the tests |
| 2.1 | Code | See the code |
| 2.2 | Extensive tests | See the tests & run them |
| 2.3 | Extensive docs | Read the docs |
| 3 | TNB chain scanner to scan the chain and input memos into the system, building up the state | Check out the API, documentation and run the tests |
| 3.1 | Code | See the code |
| 3.2 | Extensive tests | See the tests & run them |
| 3.3 | Extensive docs | Read the docs |

#### How long do you estimate for the MVP to complete?
2-3 weeks

#### Project Wallet
f1decb80339a4bb6c089b77cbac553e23a6ca86b0cfc64adb8c8eb8f8b57d815

**Comment by mrbusysky** [comment]
There is literally no point in this project.

The points system was made so people could store this data in the chain outside of memo. Memos would only be needed for item purchases and the other data would be stored as a custom transaction on the chain. This would be combining two systems causing bloat for normal nodes.

This would just bloat the normal transactions database.

Not also mentioning it would be costly since every transaction costs something making it unscalable.
The whole point of the points system is because they can burn these and they refill them making games free.

As for memo reading, this could easily be added to the python or js libraries which is already being done now.

Memos should never be used for chat storage or item state/ character state storage.

Here is a document on the system come beta:
https://docs.google.com/document/d/1AnRnUHQ1QeAbWma2dDSYtfQNX0dwp8dbvGPDJTPvYWo/edit


Edit- Also exchanges would not be very happy about having to store everyone's trash on their nodes.

**Comment by Kycermann** [comment]
> There is literally no point in this project.
> 
> The points system was made so people could store this data in the chain outside of memo. Memos would only be needed for item purchases and the other data would be stored as a custom transaction on the chain. This would be combining two systems causing bloat for normal nodes.
> 
> This would just bloat the normal transactions database.
> 
> Not also mentioning it would be costly since every transaction costs something making it unscalable. The whole point of the points system is because they can burn these and they refill them making games free.
> 
> As for memo reading, this could easily be added to the python or js libraries which is already being done now.
> 
> Memos should never be used for chat storage or item state/ character state storage.
> 
> Here is a document on the system come beta: https://docs.google.com/document/d/1AnRnUHQ1QeAbWma2dDSYtfQNX0dwp8dbvGPDJTPvYWo/edit
> 
> Edit- Also exchanges would not be very happy about having to store everyone's trash on their nodes.

I don't see any difference between your proposal and mine- except that my format works on the chain right now and stores data more efficiently. In beta, points can be used for free transactions, and fees will go down anyway once we introduce decimal points and decentralised banks that compete on fees. What am I missing?

**Comment by mrbusysky** [comment]
> 
> 
> > There is literally no point in this project.
> > The points system was made so people could store this data in the chain outside of memo. Memos would only be needed for item purchases and the other data would be stored as a custom transaction on the chain. This would be combining two systems causing bloat for normal nodes.
> > This would just bloat the normal transactions database.
> > Not also mentioning it would be costly since every transaction costs something making it unscalable. The whole point of the points system is because they can burn these and they refill them making games free.
> > As for memo reading, this could easily be added to the python or js libraries which is already being done now.
> > Memos should never be used for chat storage or item state/ character state storage.
> > Here is a document on the system come beta: https://docs.google.com/document/d/1AnRnUHQ1QeAbWma2dDSYtfQNX0dwp8dbvGPDJTPvYWo/edit
> > Edit- Also exchanges would not be very happy about having to store everyone's trash on their nodes.
> 
> I don't see any difference between your proposal and mine- except that my format works on the chain right now and stores data more efficiently. In beta, points can be used for free transactions, and fees will go down anyway once we introduce decimal points and decentralised banks that compete on fees. What am I missing?

Your system stores this in the transaction database causing bloat. Also, it is unscalable.

Exchanges do not want to host our bloat.

The points system was designed with this in mind.

**Comment by Kycermann** [comment]
> > > There is literally no point in this project.
> > > The points system was made so people could store this data in the chain outside of memo. Memos would only be needed for item purchases and the other data would be stored as a custom transaction on the chain. This would be combining two systems causing bloat for normal nodes.
> > > This would just bloat the normal transactions database.
> > > Not also mentioning it would be costly since every transaction costs something making it unscalable. The whole point of the points system is because they can burn these and they refill them making games free.
> > > As for memo reading, this could easily be added to the python or js libraries which is already being done now.
> > > Memos should never be used for chat storage or item state/ character state storage.
> > > Here is a document on the system come beta: https://docs.google.com/document/d/1AnRnUHQ1QeAbWma2dDSYtfQNX0dwp8dbvGPDJTPvYWo/edit
> > > Edit- Also exchanges would not be very happy about having to store everyone's trash on their nodes.
> > 
> > 
> > I don't see any difference between your proposal and mine- except that my format works on the chain right now and stores data more efficiently. In beta, points can be used for free transactions, and fees will go down anyway once we introduce decimal points and decentralised banks that compete on fees. What am I missing?
> 
> Your system stores this in the transaction data base causing bloat. Also, it is unscalable.
> 
> Exchanges do not want to host our bloat.

So does Ethereum. Exchanges seem fairly happy with it.

**Comment by mrbusysky** [comment]
> 
> 
> > > > There is literally no point in this project.
> > > > The points system was made so people could store this data in the chain outside of memo. Memos would only be needed for item purchases and the other data would be stored as a custom transaction on the chain. This would be combining two systems causing bloat for normal nodes.
> > > > This would just bloat the normal transactions database.
> > > > Not also mentioning it would be costly since every transaction costs something making it unscalable. The whole point of the points system is because they can burn these and they refill them making games free.
> > > > As for memo reading, this could easily be added to the python or js libraries which is already being done now.
> > > > Memos should never be used for chat storage or item state/ character state storage.
> > > > Here is a document on the system come beta: https://docs.google.com/document/d/1AnRnUHQ1QeAbWma2dDSYtfQNX0dwp8dbvGPDJTPvYWo/edit
> > > > Edit- Also exchanges would not be very happy about having to store everyone's trash on their nodes.
> > > 
> > > 
> > > I don't see any difference between your proposal and mine- except that my format works on the chain right now and stores data more efficiently. In beta, points can be used for free transactions, and fees will go down anyway once we introduce decimal points and decentralised banks that compete on fees. What am I missing?
> > 
> > 
> > Your system stores this in the transaction data base causing bloat. Also, it is unscalable.
> > Exchanges do not want to host our bloat.
> 
> So does Ethereum. Exchanges seem fairly happy with it.

Only because they had no choice in the matter. And eth is expensive also not realtime

**Comment by mrbusysky** [comment]
A system is literally being made for beta with this in mind. All this will do is bloat the network, and is not scalable at all. This is why eth is having to change how it does things. They are separating the currency and transactions for dapps.

Keeping these separate allows nodes to be modular, allowing certain businesses to not have to host what they deem useless data and those who wish to interact with the dapp level to host that data if they so choose.

**Comment by Kycermann** [comment]
> A system is literally being made for beta with this in mind. All this will do is bloat the network, and is not scalable at all. This is why eth is having to change how it does things. They are separating the currency and transactions for dapps.
> 
> Keeping these separate allows nodes to be modular, allowing certain businesses to not have to host what they deem useless data and those who wish to interact with the dapp level to host that data if they so choose.

Solana is managing 50k TPS with normal transactions- which this is using as well. Isn't ETH slow due to on-chain smart contracts?

**Comment by mrbusysky** [comment]
> 
> 
> > A system is literally being made for beta with this in mind. All this will do is bloat the network, and is not scalable at all. This is why eth is having to change how it does things. They are separating the currency and transactions for dapps.
> > Keeping these separate allows nodes to be modular, allowing certain businesses to not have to host what they deem useless data and those who wish to interact with the dapp level to host that data if they so choose.
> 
> Solana is managing 50k TPS with normal transactions- which this is using as well. Isn't ETH slow due to on-chain smart contracts?

They are separating the chain features. Dapp/smart contacts with be on a side chain. And main currency transfers will be on the other. Because it causes congestion. This would to do the same to our chain, the cost for games using normal transactions is too high to keep them scalable. There is a reason eth is only so big and the cost is one reason. No one wants to pay every time they do something.

What you are proposing is going down the same path that caused eth to have issues. And exchanges/node operators complain all the time about data they find useless.

Also what you suggest would bloat the database making it more expensive for normal people to run nodes. Because they need more storage and more resources to process the spam this would cause on normal transactions.
