### ISSUE TITLE
DTNB-JS 

### ISSUE THREAD

**Issue by mrbusysky** [thenewboston-developers/Project-Proposals#335]
# Project Details

#### How would you describe your project?
Taking over the -js repo/npm so it can be maintained and updated since the main team doesn't have the time. i have already talked to bucky and justin k about wanting to take over the javascript codebase so the main team can just focus on beta.

#### What problem does this project solve?
Fast updates to match the new chains API development so it is ready on day one.

#### Who is the target market?
javascript developers

#### How will this project benefit the network and/or the community?
Make sure new features and upkeep of the API codebase.

#### How is this project centered around thenewboston?
Keep the codebase up to date

#### What is the estimated completion date for this project? (rough estimates are acceptable)
A few days after the API is completed for the beta, but we will also clean up the current code to work better and be easier to use.

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
Not really a detailed roadmap since we will start from an existing codebase more than likely.

#### What is your Discord username?
MrSky#5242

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)
https://github.com/Keysign-Wallet/DTNB-JS

**Comment by tspearing** [comment]
@mrbusysky, please use the code in any way you like. We're happy to provide TNBC for any updates which are made but we will keep ownership of the library.
