### ISSUE TITLE
TNB Heroes - Backend - 2

### ISSUE THREAD

**Issue by Kycermann** [thenewboston-developers/Project-Proposals#336]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/226

#### Detailed log of all completed objectives including valid proof of work.
Objectives table is in the link above.

Code: https://github.com/Kycermann/TNB-Heroes

#### Project Wallet
f1decb80339a4bb6c089b77cbac553e23a6ca86b0cfc64adb8c8eb8f8b57d815

**Comment by manishram** [comment]
Approved for 125k TNBC
