### ISSUE TITLE
Nyord

### ISSUE THREAD

**Issue by adarshkr01** [thenewboston-developers/Project-Proposals#337]
# Nyord - Crypto + Fiat Expense Tracker

#### How would you describe your project?
Money is extremely volatile. If not kept a proper record of, one can easily mismanage their funds, forget essential bills and payments, spend more than the required amount on unnecessary shopping, etc.

Nyord (Website/App) solves the problem of tracking these expenses for the user. Since TNB is more likely to become an everyday currency, the requirement to keep a track of the amount spent (or to be spent), bills paid (or to be paid), essentials bought (or to be bought), etc can definitely make life slightly easier for everyone.

A web app that helps users track both their crypto (MVP: TNBC) and fiat expenses.

#### What problem does this project solve?
- Keeping a track of monthly essential spending
- Keeping track of free-spending
- Helping users meet their saving goals
- Reminders for weekly and monthly payments
- Financial Calendar to track and manage expenses
- Using graphs for better visualization and facts about user's spending pattern

#### Who is the target market?
The project's target market is

- normal users who are looking to make their life less frustrating by managing their expenses
- people looking to make the most out of their money
- project managers who have to hand out payments to people working for them
- freelancers who have earning goals
- businesses that have a manual earning/selling system

#### How will this project benefit the network and/or the community?
- It aims to provide project managers a way to track the money spent during the development of their projects
- The project aims to provide the people of the community a chance to earn TNBC
- In the long run, the project aims to provide the normal users a way to track their expenses when TNB becomes a part of the economy and infrastructure (daily usage coins)
- (Possible feature) It aims to provide the government a way to track the money released by the treasury (in case it is required to be tracked)

#### How is this project centered around thenewboston?
The project will keep a track of TNB spending of users, along with their fiat expenses.

#### What is the estimated completion date for this project? (rough estimates are acceptable)
MVP should be completed by May 2022

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
- Project Planning (User flows and Wireframing)
- Logo Designing and Web app UI/UX
- Backend Development
- Frontend Development
- Staging and Testing (Test Launch)
- Full Launch

#### What is your Discord username?
Niekon01#0116

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)
TBA

# Milestone 1 - Minimum Viable Product (MVP) Details

The MVP aims to include the following features:
- Account Creation
- Linking wallet to account
- Adding/removing/editing expenses
- Spendings based on categories
- Balances - Fiat and TNBC
- Checking monthly expenses and insights
- Monthly reports

---

#### Objectives for MVP

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 | MVP | They can verify the working of the project during the staging phase |

#### How long do you estimate for the MVP to complete?
3-4 Months

#### Project Wallet
7dd8233cacae817b636a3790bbab9731535787955a5767aada4a193f0ee135b7

**Comment by wakawakathedev** [comment]
Link for inspiration btw. ☝️ 

- https://www.accointing.com/app/wallets
- https://mint.intuit.com/
- https://monzo.com/

**Comment by tspearing** [comment]
Approved.
