### ISSUE TITLE
Origami - MVP - 1

### ISSUE THREAD

**Issue by wakawakathedev** [thenewboston-developers/Project-Proposals#342]
#### Link to the milestone and objectives table.
[Proposal](https://github.com/thenewboston-developers/Projects/issues/244)

#### Detailed log of all completed objectives including valid proof of work.
Site: https://origami-beta.vercel.app/
Repo: https://github.com/wakawakathedev/origami

#### Project Wallet
baa336bca22c7590256a86c002e4dbe6c1f1c1f6c0a0fd3f0681eecb2cad0787

**Comment by wakawakathedev** [comment]
Wanted to highlight the following:

1. QR Code generation.
2. Offline Support.
3. PWA Support.
4. Vercel Deployment.

Follow up Milestone would be:

- [ ] Wallet Design Choices
- [ ] Marketing UI (i.e. make it more consumer focused) - ie. add design from Proposal
- [ ] Show basic tutorial
- [ ] Add Keysign JSON/QRCode format support (JSON.stringify account)

**Comment by tspearing** [comment]
@wakawakathedev, thanks for submitting this.

One issue we're seeing, once the keys are generated, if a connection is reestablished, the keys disappear. This could lead to lost coins if the user hasn't saved. Is there a way we can keep security strong without risking lost funds?

Also, this [issue](https://github.com/thenewboston-developers/Projects/issues/277) included graphic designs which are not used in this iteration. Can they be added?

**Comment by wakawakathedev** [comment]
If a connection is established - there is a risk that the keys could be leaked on a compromised browser 
(say if the user has malware that has a video capture of the users desktop).

IF the user returns back online - they are at risk of their keys being leaked.

We can improve upon this on a follow-up PR.

---

> Also, this issue included graphic designs which are not used in this iteration. Can they be added?

I'll do it in a follow up (next milestone) - have higher priority things to get done first.

**Comment by tspearing** [comment]
@wakawakathedev, I'd have assumed that malware could record even if there is no connection and send later. How about we add a "Download" button which creates a PDF of the wallet? This could be done in the next milestone.

**Comment by manishram** [comment]
Approved for15k TNBC.

**Comment by wakawakathedev** [comment]
ok dokie @tspearing - these are good comments and i'll add them to the next milestone. 🙏 Thanks!
