### ISSUE TITLE
Update TNB ALPHA

### ISSUE THREAD

**Issue by mrbusysky** [thenewboston-developers/Project-Proposals#345]
# Project Details

#### How would you describe your project?
TNB ALPHA is taking way too long to update and it's holding back projects. Keysign wants to bring in some blockchain devs to solve the issue that is holding people's projects back. Also to make it so user's private information isn't blasted all over the internet which allows people to link your wallet to your home address.

#### What problem does this project solve?
It will update the nodes on the chain to be capable of using and storing HTTPS links and some features the alpha needs updating.

#### Who is the target market?
The whole community

#### How will this project benefit the network and/or the community?
Make sure new features and upkeep of the network

#### How is this project centered around thenewboston?
Keep the codebase up to date and features updating as fast as possible so no one is delayed. Also, it's a plain as day security update.

#### What is the estimated completion date for this project? (rough estimates are acceptable)
This depends when or if the main team thinks it's safe to deploy.

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
Update all related repo's
* Update bank repo
* Update thenewboston-python repo
* Update validator

Will update
* Add migrations for required repo's 
* Storage of secure connections
* Update memo size to 256 characters for e-commerce apps.
* Update attack using bulk transactions which allows users to pay 1 fee for unlimited transactions.

#### What is your Discord username?
MrSky#5242

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)
The links to repos will be anything mrbusysky/reponame

Link to scope: https://docs.google.com/document/d/1nqaoXl4-xfuQtEd6yVSrk30DXhDlxzZUkxYr3DCfIoY/edit

**Comment by buckyroberts** [comment]
Alpha is now in maintenance mode: https://discord.com/channels/774574985510518806/850597347238477844/908492753908932628
