### ISSUE TITLE
TNBC Subscriptions

### ISSUE THREAD

**Issue by hackerrahul** [thenewboston-developers/Project-Proposals#347]
#### How would you describe your project?
TNBC Subscriptions - A method for SaaS owners to enable subscription of their product using TNBC coins directly.

#### What problem does it solve?
Even it is fast but at the time of recurring payment user has to click the button again and pay using TNBC on checkout, if this is possible, then user can just set the subscription with TNBC based on the product value and it will convert to TNBC coins and charge user TNBC coins based on the converted value.

#### Who is the target market?
SaaS Products, Digital E-Commerce

#### What do you think is the opportunity of this project?
It will be a great thing, As it will reduce the pain of user to pay again at the time of recurring payment so it will just automate the flow.

#### Are there any competitors?
No One

#### What are your goals and objectives?
To setup Recurring payments in TNBC and reduce the subscription pain

#### How will you evaluate project success?
on a scale of 1-10, i think this will be a 10 (great product).

**By posting this issue, I (author of this issue) allow my project idea to be used by other people for any commercial as well as non-commercial purposes and I'll not be liable for misuse of my idea.**

**Comment by mrbusysky** [comment]
https://www.reddit.com/r/thenewboston/comments/q34q42/decentralized_subscriptions_payments_with_keysign/
