### ISSUE TITLE
PointAccess

### ISSUE THREAD

**Issue by adarshkr01** [thenewboston-developers/Project-Proposals#354]
# Project Details

#### How would you describe your project?
PointAccess is a service that will help users link their TNB account with 3rd party applications.

#### What problem does this project solve?
Whenever user wants to link their account with a bot or a website, they are required to send 1 coin to some wallet with specific memo, or provide their signing key. All of these are a hassle and have higher risk of losing coins or leaking signing key. As TNB grows, more and applications will want users to link their account, thus making the process repetitive.

PointAccess is looking to remove this redundancy and make linking TNB account with other applications easy and fast. When users will authorize other applications to link their account, they will also be able to keep track of which applications have their account number in their database. 

#### Who is the target market?
The target market will be both the users and applications who want to link accounts of their users.

#### How will this project benefit the network and/or the community?
The project will remove the hassle of linking TNB accounts by sending coins or exposing their Signing key.

#### How is this project centered around thenewboston?
The project is centered around TNB accounts

#### What is the estimated completion date for this project? (rough estimates are acceptable)
March 2022

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
ANSWER HERE

#### What is your Discord username?
Niekon#0116

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)
- OPTIONAL ATTACHMENT HERE
- OPTIONAL ATTACHMENT HERE
- OPTIONAL ATTACHMENT HERE

# Milestone 1 - Minimum Viable Product (MVP) Details

Please include a detailed breakdown of the MVP including a list of all quantifiable objectives. Upon 
completion of the MVP, each objective will be reviewed by thenewboston team and once all objectives have been 
verified as completed, amount of coins will be negotiated. 

Note that all future detailed milestone breakdowns will be written as a separate GitHub issue. Only the first 
milestone which is for MVP is included in this project proposal.

---

#### MVP Description
PointAccess will be a webapp

#### Objectives for MVP

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 | TBA | TBA |

#### How long do you estimate for the MVP to complete?
2-3 months

#### Project Wallet
5225894884a608feed3f676d0245dbecce903f58e4bb16a53ef510be5fdfe531

**Comment by tspearing** [comment]
@Niekon01, we aren't clear how this would work. Can you further explain how the solution would work? Please also fill out the objective table.

**Comment by adarshkr01** [comment]
[PointAccess.pdf](https://github.com/thenewboston-developers/Projects/files/7596373/PointAccess.pdf)
This is a high level of how the application will work @tspearing 

Please let me know if you need more information. Thanks.

**Comment by tspearing** [comment]
@Niekon01, this is on the list to be discussed on Monday. By closing do you no longer want to do it?

**Comment by adarshkr01** [comment]
Hi @tspearing, I will be posting an updated version of this soon. Thank you.

**Comment by tspearing** [comment]
@Niekon01, sounds good, reopen when ready.
