### ISSUE TITLE
TNBPAY - Milestone 5

### ISSUE THREAD

**Issue by olowudaniel1** [thenewboston-developers/Project-Proposals#357]
#### Link to the milestone and objectives table.
#272 

#### Detailed log of all completed objectives including valid proof of work.
LIVE TESTING: https://magento.codextblog.com/push-it-messenger-bag.html Sign in with demo customer account
GITHUB:  https://github.com/TNB-PAY/Magento

Images and demo:
![video](https://user-images.githubusercontent.com/79472442/142872926-a3035e38-9bc2-46e6-9c68-7750f0777d11.gif)
![Screenshot from 2021-11-22 13-24-11](https://user-images.githubusercontent.com/79472442/142872893-7e1442ad-053f-49a8-891d-6c47d030e550.png)

![Screenshot from 2021-11-10 22-29-49](https://user-images.githubusercontent.com/79472442/142873056-b38744fe-88e2-4e69-84f0-e101bd216e43.png)

#### Project Wallet
86ee75d4cea77ca8339cc97f5e7426a3434d9f91465cd441c0c7593bd852e955

**Comment by manishram** [comment]
Hey @olowudaniel1 

https://github.com/TNB-PAY/Magento/blob/f32a4a8e60378eccfaaf7d328c93ef4b7a445290/Helper/Data.php#L72
I suggest not using hardcoded IP Addresses for the bank directly into the source code. It may break the plugin if that particular bank goes down.

**Comment by tspearing** [comment]
Approved for 50000 TNBC. However, please update the following: 
The code for the bank shouldn't be hardcoded
The documentation URL in the readme on github should return a proper page rather than 404
