### ISSUE TITLE
TNBC Analytics - Testing and Deployment - 03 

### ISSUE THREAD

**Issue by SazidAhmed** [thenewboston-developers/Project-Proposals#359]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/306

#### Detailed log of all completed objectives including valid proof of work.

We've finally completed our MVP and made it production ready with some new designs and features. We've also deployed to a server to make it publicly accessible.

To verify new design and features we're including both the old and new version.
Old version is here: https://tnb-analytics-old.netlify.app/
New version is here: http://tnbanalytics.com/

Tasks of the objective of the milestone are given below with proof of works.

1. Code optimization for better performance on both backend and frontend
Proof of work : Unnecessary Codes have been removed and organized by new folder structures. We verify the work we're providing both frontend and backend repo
Frontend Repository : https://github.com/Techminate/TNBC-Analytics-Frontend
Backend Repository : https://github.com/Techminate/TNBC-Analytics-Backend

2. fixing the bugs available in govt and treasury statistics.
Proof of work : Bugs have been fixed. To verify please visit : http://tnbanalytics.com/

3. Improvement of graphs
Proof of work : 
To verify please visit : 
http://tnbanalytics.com/
http://tnbanalytics.com/treasury
http://tnbanalytics.com/government

4. add appropriate contents on the FAQs page
Proof of work : We've added contents related to TNBC Treasury,  Government, Projects, Bounties etc.
To verify please visit :  http://tnbanalytics.com/faq

5. add a one click redirection to github issue from table data
Proof of work : We've added github link to the table. Now anyone go to the github issue related to the payment by clicking on the link.
To verify please visit :  http://tnbanalytics.com/government

6. Buy a domain name as "tnbcanalytics.com" and host the production ready "TNBC Analytics".
Proof of work : We've bought a domain as "tnbanalytics.com" and hosted the app to a server.
To verify please visit :  http://tnbanalytics.com

#### Project Wallet
a5dbcded3501291743e0cb4c6a186afa2c87a54f4a876c620dbd68385cba80d0

**Comment by tspearing** [comment]
@SazidAhmed, looks good. Can you add a link on the FAQ page in the question "How do I propose a project?"

**Comment by manishram** [comment]
Hey @SazidAhmed
1. The GitHub issue id in the distribution section of [Government](http://tnbanalytics.com/government) page takes the user to [Website](https://github.com/thenewboston-developers/Website) repo but it should take the user to [Contributor-Payments]( https://github.com/thenewboston-developers/Contributor-Payments) repo.
(**Note**: With the new payment standards we create an issue in [Contributor-Payments]( https://github.com/thenewboston-developers/Contributor-Payments) repo for all transactions going out of the Treasury or Payments Account(`6e5ea8507e38be7250cde9b8ff1f7c8e39a1460de16b38e6f4d5562ae36b5c1a`))

2. The updated memo format of the project is TNB_PROJECT_<PROJECT_PROPOSAL_ISSUE_NUMBER>_<MILESTONE_PAYOUT_ISSUE_NUMBER>. So for the payments made to the project we expect the link to point to https://github.com/thenewboston-developers/Projects/issues/**<MILESTONE_PAYOUT_ISSUE_NUMBER>** and NOT the <PROJECT_PROPOSAL_ISSUE_NUMBER>. So that users can directly find out the exact milestone payout request for that particular project payment transaction.

**Comment by SazidAhmed** [comment]
> @SazidAhmed, looks good. Can you add a link on the FAQ page in the question "How do I propose a project?"

We'll work on it

**Comment by SazidAhmed** [comment]
> Hey @SazidAhmed
> 
> 1. The GitHub issue id in the distribution section of [Government](http://tnbanalytics.com/government) page takes the user to [Website](https://github.com/thenewboston-developers/Website) repo but it should take the user to [Contributor-Payments](https://github.com/thenewboston-developers/Contributor-Payments) repo.
>    (**Note**: With the new payment standards we create an issue in [Contributor-Payments](https://github.com/thenewboston-developers/Contributor-Payments) repo for all transactions going out of the Treasury or Payments Account(`6e5ea8507e38be7250cde9b8ff1f7c8e39a1460de16b38e6f4d5562ae36b5c1a`))
> 2. The updated memo format of the project is TNB_PROJECT_<PROJECT_PROPOSAL_ISSUE_NUMBER>_<MILESTONE_PAYOUT_ISSUE_NUMBER>. So for the payments made to the project we expect the link to point to https://github.com/thenewboston-developers/Projects/issues/**<MILESTONE_PAYOUT_ISSUE_NUMBER>** and NOT the <PROJECT_PROPOSAL_ISSUE_NUMBER>. So that users can directly find out the exact milestone payout request for that particular project payment transaction.

We'll work on it

**Comment by tspearing** [comment]
@SazidAhmed, let us know with a comment here when ready for another review.

**Comment by SazidAhmed** [comment]
> > @SazidAhmed, looks good. Can you add a link on the FAQ page in the question "How do I propose a project?"
> 
> We'll work on it

link and redirect to the website has been added 
Please check here : http://tnbanalytics.com/faq

**Comment by SazidAhmed** [comment]
> > Hey @SazidAhmed
> > 
> > 1. The GitHub issue id in the distribution section of [Government](http://tnbanalytics.com/government) page takes the user to [Website](https://github.com/thenewboston-developers/Website) repo but it should take the user to [Contributor-Payments](https://github.com/thenewboston-developers/Contributor-Payments) repo.
> >    (**Note**: With the new payment standards we create an issue in [Contributor-Payments](https://github.com/thenewboston-developers/Contributor-Payments) repo for all transactions going out of the Treasury or Payments Account(`6e5ea8507e38be7250cde9b8ff1f7c8e39a1460de16b38e6f4d5562ae36b5c1a`))
> > 2. The updated memo format of the project is TNB_PROJECT_<PROJECT_PROPOSAL_ISSUE_NUMBER>_<MILESTONE_PAYOUT_ISSUE_NUMBER>. So for the payments made to the project we expect the link to point to https://github.com/thenewboston-developers/Projects/issues/**<MILESTONE_PAYOUT_ISSUE_NUMBER>** and NOT the <PROJECT_PROPOSAL_ISSUE_NUMBER>. So that users can directly find out the exact milestone payout request for that particular project payment transaction.
> 
> We'll work on it

Github issue id has been updated following your suggestion 
Please review the updates : http://tnbanalytics.com/government

**Comment by SazidAhmed** [comment]
> @SazidAhmed, let us know with a comment here when ready for another review.

Ready for another review. Please review the updates : 
http://tnbanalytics.com/faq
http://tnbanalytics.com/government

**Comment by tspearing** [comment]
Approved for 40k TNBC. Let us know your thoughts.

**Comment by SazidAhmed** [comment]
> Approved for 40k TNBC. Let us know your thoughts.
We always respect the decision of Core team.
Thank You.
