### ISSUE TITLE
Vionik

### ISSUE THREAD

**Issue by adarshkr01** [thenewboston-developers/Project-Proposals#364]
# Project Details

#### How would you describe your project?
Vionik aims to be a Payment Interface. It will protect users’ account numbers. This will help users to use applications without having to trust them to fairly use their sensitive information, and amply protect them.

#### What problem does this project solve?
- Reduce the number of times user sends coins or enter their signing key to multiple applications they use in order to verify their account.
- Make linking of accounts on other applications easy.
- Prevent applications from storing users’ accounts in their database.
- Act as a payment interface between applications and users (when applications send coins to users).
- Prevent the association of identity of users with their accounts by implementing a scheduling system.

#### Who is the target market?
TNB users

#### How will this project benefit the network and/or the community?
The project aims to protect users' account numbers and identity

#### What is the estimated completion date for this project? (rough estimates are acceptable)
April 2022

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
- Wireframing and User Flow design
-  Logo Design and UI/UX
- Backend logic and Web application development

#### What is your Discord username?
Niekon#0116

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)
- https://docs.google.com/document/d/1IPnZS_JJVj1P2AhA-qaX1t3Wn42kAaLoCU5EZmz3dss/edit?usp=sharing
- https://drive.google.com/file/d/1ZxWqzyLrEt0wOCTUTx8y4S2Yoz3hHRji/view

# Milestone 1 - Minimum Viable Product (MVP) Details

Please include a detailed breakdown of the MVP including a list of all quantifiable objectives. Upon 
completion of the MVP, each objective will be reviewed by thenewboston team and once all objectives have been 
verified as completed, amount of coins will be negotiated. 

Note that all future detailed milestone breakdowns will be written as a separate GitHub issue. Only the first 
milestone which is for MVP is included in this project proposal.

---

#### MVP Description
The MVP will be a Web Application

#### Objectives for MVP

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 | MVP | This can be verified during the staging of the project |
| 2 | Add support for multiple emails | Staging of version 2 |
| 3 | Deposit and transfer support | Staging of version 3 |

#### How long do you estimate for the MVP to complete?
4 Months

#### Project Wallet
7dd8233cacae817b636a3790bbab9731535787955a5767aada4a193f0ee135b7

**Comment by adarshkr01** [comment]
To clarify, there are two ways to link accounts:
- Sending coins to an address with some MEMO (Recommended): Users can choose this option, get a unique MEMO and an address where they need to send at least one coin in order to verify and link their account.
- Entering their Signing Key: The system will take this signing key, generate the corresponding public key, and save the public key. The signing key is a one-time verification method that the account a user is trying to link is their own, and is not stored in the database. This was to facilitate linking of accounts with zero balance + one-time use accounts.

**Comment by tspearing** [comment]
Approved.
