### ISSUE TITLE
Maakay Discord Bot - Multi Server Support with shared fees - 3

### ISSUE THREAD

**Issue by hussu010** [thenewboston-developers/Project-Proposals#366]
#### Link to the milestone and objectives table.
[Milestone Proposal](https://github.com/thenewboston-developers/Projects/issues/348)

#### Detailed log of all completed objectives including valid proof of work.
| # | Objective             | How can auditors verify milestones?     |
| - | --------------------- | -------------------------------------- |
| 1 | Share the fees with server owners  | Invite the bot into your discord server, perform commands the require fees, and check the balance statistics |
| 2 | Implement `/admin set_withdrawal_address address: ADDRESS` command | Use the command |
| 3 | Implement `/admin info` command | Use the command |
| 4 | Implement `/admin withdraw amount: AMOUNT` command | Use the command |
| 5 | Permission management for server admins | A separate role will be created by the bot that'll have the permissions to use /admin command |
| 6 | Implement `/admin transactions` command | List all the withdrawals performed by the admins of the server |

Staging discord bot invitation link (DM me before inviting it into your discord server since I need to run on my local machine): https://discord.com/api/oauth2/authorize?client_id=891676665770541066&permissions=268435456&scope=bot%20applications.commands

#### Project Wallet
79c0d308e31b9c4cf0f2bdaae65e2d8476c355084035ee11755facaa9597ff98

**Comment by manishram** [comment]
Approved for 25K.
