### ISSUE TITLE
TheNewLawyers

### ISSUE THREAD

**Issue by ThatTNBGuy** [thenewboston-developers/Project-Proposals#368]
# Project Details

#### How would you describe your project?
We want to build a platform(Website for now) where people can get a lawyer consultancy service from professional lawyers and they can purchase this service with TNBC.

#### What problem does this project solve?
This project(or platform) will allow people holding TNB coins to utilize it for real services like lawyer consultancy. Lawyers are too expensive these days. With our business model, we'll provide a world-class lawyer with the amount of TNBC coins that people can earn by doing even minor contributions to the TNB ecosystem.

#### Who is the target market?
This project targets everyone who may want to get lawyer service at an affordable cost by paying through TNBC coins.

#### How will this project benefit the network and/or the community?
1. This project is going to give real value to TNBC.
2. People working on projects and need lawyers for their startup projects can take advice from our lawyers.
3. General people need lawyers for their day-to-day issues.

#### How is this project centered around thenewboston?
This project is going to provide real service to people in exchange for TNBC.

#### What is the estimated completion date for this project? (rough estimates are acceptable)
7 days (Approx.)

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
ANSWER HERE

#### What is your Discord username?
ThatGuy#4428

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)
- OPTIONAL ATTACHMENT HERE
- OPTIONAL ATTACHMENT HERE
- OPTIONAL ATTACHMENT HERE

# Milestone 1 - Minimum Viable Product (MVP) Details

Please include a detailed breakdown of the MVP including a list of all quantifiable objectives. Upon 
completion of the MVP, each objective will be reviewed by thenewboston team and once all objectives have been 
verified as completed, amount of coins will be negotiated. 

Note that all future detailed milestone breakdowns will be written as a separate GitHub issue. Only the first 
milestone which is for MVP is included in this project proposal.

---

#### MVP Description
This MVP will be a complete website. People would be able to schedule meeting with lawyers by paying TNBC coins.

#### Objectives for MVP

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 | Appointment booking | Can be verified through the website |
| 2 | TNB payment integration | Can be verified through the website |
| 3 | Video or Audio call | Can be verified through the website |

#### How long do you estimate for the MVP to complete?
7 days (Approx.)

#### Project Wallet
1a130ff4250002a4886728a1790cabead4efb14c456a600ae5f0cef59d634674

**Comment by ThatTNBGuy** [comment]
Few things we want to let the team know:
1. Since this lawyer service proving project is going to deal with legal issues, thenewboston is not going to be responsible for any issues related to our service. 
2. If the team approves this project, we request you to give us an estimate of how much we can get funded. (We need this information because we may spend lots of money hiring lawyers and if we don't get enough funds to run this project then we would be at a great loss. )

Thank you
TheNewLawyers Team.

**Comment by tspearing** [comment]
Hi @ThatTNBGuy, we have a few questions about this project.
1) Can you further explain he business plan? "We may spend lots of money hiring lawyers", does this mean that the lawyers will be hired by you? Please explain he utility flow.
2) Please note that we already have TNBPay which has wordpress and magento integration with TNBC

**Comment by wakawakathedev** [comment]
Unsure if this should be a project - 

- I'd say that if the original poster is a lawyer, and is willing to accept tnbc, then technically it would be a web app for their own benefit (rather than a project). 
- The other issue is that lawyers operate in different jurisdiction and unless the lawyer operates in their own company (i.e. self-employed) it would make it difficult for corporate lawyers to justify accepting crypto to the partners. _technically_ you could say that this is pro-bono work, however for tax purposes, this would need to be logged the respective counties tax laws.

Mirroring @tspearing - TNBPay ad KeysignPay are two existing payment integrations for online web payments.
