### ISSUE TITLE
Tnbc Games - Milestone 3

### ISSUE THREAD

**Issue by olowudaniel1** [thenewboston-developers/Project-Proposals#369]
#### Link to the milestone and objectives table.
#316 

#### Detailed log of all completed objectives including valid proof of work.
Hosted on Heroku
https://tnbc-games.herokuapp.com/

Here are some pages you might find difficult to navigate to

https://tnbc-games.herokuapp.com/leaderboard
https://tnbc-games.herokuapp.com/profile

APIs are in the Github repo

#### Project Wallet
86ee75d4cea77ca8339cc97f5e7426a3434d9f91465cd441c0c7593bd852e955

**Comment by tspearing** [comment]
@olowudaniel1, we can't load the page:
![image](https://user-images.githubusercontent.com/77364430/144543357-7a4abb1a-f334-44ec-87aa-102a6ff4fb58.png)

**Comment by tspearing** [comment]
@olowudaniel1, this is milestone 3, but it references back to milestone 2 which is not paid. Should this be for milestone 2?

**Comment by olowudaniel1** [comment]
@tspearing Yeah, it is milestone 3, link updated. Please try the site again, going at my end

**Comment by tspearing** [comment]
@olowudaniel1, Several issues:
1) By registering you agree to tnbCrow’s terms of using the tnbc games platform and privacy policy. - this is on the sign up page. It isn't clear what it means.
2) The discord button on the index doesn't do anything
3) Don't see FAQ or leaderboard
4) The site is not responsive on small screens
5) "More" in header leads to /shop
6) Password text isn't hidden - input type should be Password
7) Sign up using discord isn't working
8) Sign up using google isn't working
9) Lorum Ipsum in the page description
10) Unable to view individual tournament pages

There's more but it looks like this site isn't ready for review.

**Comment by olowudaniel1** [comment]
1. Will fix this
2. We are focused on the main tasks now. We could always embed the discord link here anytime
3.  Leaderboard: http://tnbc-games.herokuapp.com/leaderboard FAQ would be designed
4. Will look into this again
5. The navigation will be updated, however, we have nothing for "more" yet
6. Noted
7. Will check this again, it should work
8. Should work, will check again
9. Yeah, most of the contents hasn't been decided yet
10.  This is for milestone 2.  The single tournament page differs based on games. However, don't know if you saw this: http://tnbc-games.herokuapp.com/my-tournament

The milestone objectives will be scrutinized  again and I will ensure we meet all objectives are met

**Comment by olowudaniel1** [comment]
@tspearing 
All fixes made https://tnbc-games.herokuapp.com/

Listed below are some pages you might find difficult to navigate

https://tnbc-games.herokuapp.com/faq
http://tnbc-games.herokuapp.com/leaderboard 
http://tnbc-games.herokuapp.com/my-tournament
https://tnbc-games.herokuapp.com/profile

**Comment by manishram** [comment]
Hey @olowudaniel1, some of the pages/features are still missing or they just have static data. Some of the buttons are not functional. Please fix them and let's have google meet and go through your project pages, objectives, and features.

**Comment by manishram** [comment]
Hey @olowudaniel1, here are the issues that still need to be addressed:
1. These objectives don't seem like exists:
a. Endpoint to display users' information
b. CRUD endpoint for Games mgt
c. CRUD endpoint for Tournaments mgt

2. Forgot password is in the menu after login which is totally redundant. It is supposed to be on the sign in page but it is missing over there.

3. The menu that opens on clicking the top right corner button (after signing in) doesn't close unless we navigate to another page.

4. None except the first feature seems to be existing as described in the approved milestone:
![image](https://user-images.githubusercontent.com/22790904/147184972-061e0fec-4820-4d04-ab97-342db49a2b3f.png)
