### ISSUE TITLE
Jumpy Coin - MVP - 1

### ISSUE THREAD

**Issue by hayderkharrufa** [thenewboston-developers/Project-Proposals#370]
#### Link to the milestone and objectives table.
[#361](https://github.com/thenewboston-developers/Projects/issues/361)

#### Detailed log of all completed objectives including valid proof of work.
Download from Play Store:
https://play.google.com/store/apps/details?id=org.iamhaydara.jumpycoin

APK:
https://drive.google.com/file/d/1YWUVfjhA8FKfOPkgEa_aeLvEkpXJgnMg/view?usp=sharing

| # | Objective             | Status     |
| - | --------------------- | -------------------------------------- |
| 1 | Game design | Completed |
| 2 | UI/UX design | Completed |
| 3 | Build assets | Completed |
| 4 | Build a working prototype | Completed |
| 5 | Add payment with Keysign | Completed |
| 6 | Add audio assets | Completed |
| 7 | Test | Completed |
| 8 | Polish | Completed |
| 9 | Publish on Play Store | Completed |

#### Project Wallet
7a42c9cfc4d0f0d2ba5fe126a712f5bbe8ce20d002d427b48f7490b074b9f361

**Comment by tspearing** [comment]
Approved for 80k TNBC.
