### ISSUE TITLE
DOMAINS AND IP WORKING at the same time on nodes - Milestone - 1

### ISSUE THREAD

**Issue by mrbusysky** [thenewboston-developers/Project-Proposals#372]
#### Link to the milestone and objectives table.
[here](https://github.com/thenewboston-developers/Projects/issues/355)

#### Detailed log of all completed objectives including valid proof of work.
[PV/CV nginx](https://docs.google.com/document/d/1t1De6rK_u5o3FLnIhsaBiGZjBclKUgYOnE2j09Ibaus/edit)
[Bank nginx](https://docs.google.com/document/d/1-s1kEEQBXqKfsULIuwkLIFGiAt3UlNtVCvOrPPZDgQE/edit)
[Proof of it working](https://bank.keysign.app/confirmation_blocks)

#### Project Wallet
fe06754d2dbf23509e975809e9023b620509c1e6618472f16c9659f59e940337

**Comment by tspearing** [comment]
Approved for 6500 TNBC.

**Comment by mrbusysky** [comment]
Sure
