### ISSUE TITLE
CodeArkive - Puzzle 2

### ISSUE THREAD

**Issue by adarshkr01** [thenewboston-developers/Project-Proposals#375]
#### Link to the milestone and objectives table.
- https://github.com/thenewboston-developers/Projects/issues/375

#### Detailed log of all completed objectives including valid proof of work.
https://codearkive.pythonanywhere.com/puzzle-two/

#### Project Wallet
18c07b4227cb0993fa7a1db834834e42461a0d9f61b2b157dfbfee625bbf3de6

**Comment by tspearing** [comment]
@Niekon01, we are unable to find a project proposal this. Please create a proposal prior to the payout request.

**Comment by adarshkr01** [comment]
Hey @tspearing, here is the project proposal: https://github.com/thenewboston-developers/Projects/issues/377

**Comment by tspearing** [comment]
Approved for 45000 TNBC.
@Niekon01, when the puzzle is solved, please submit a bounty request for the 10000 TNBC.
https://github.com/thenewboston-developers/Contributor-Payments/issues/new?assignees=&labels=Bounty+Payment&template=bounty-account-refill-request.md&title=Bounty+Payment+Request+-+DD%2FMM%2FYYYY+-+TEAM_NAME
