### ISSUE TITLE
Origami - Updated Design - 2

### ISSUE THREAD

**Issue by wakawakathedev** [thenewboston-developers/Project-Proposals#376]
#### Link to original project proposal.
[Proposal](https://github.com/thenewboston-developers/Projects/issues/277)

#### Link to most recent milestone payout request.
[Payout Request](https://github.com/thenewboston-developers/Projects/issues/342)

### Proof of work
[PR](https://github.com/wakawakathedev/origami/pull/2). 
[Repo](https://github.com/wakawakathedev/origami). 

View the deployed app [here](https://origami-beta.vercel.app/). 

### Screenshots

Private Keys were blurred to obfuscate key value.

mobile | desktop | print |
--- | --- | --- 
<img width="634" alt="Screenshot 2021-12-09 at 9 44 09 PM" src="https://user-images.githubusercontent.com/89671440/145414486-990c6507-a5e6-49d4-bf32-1d6eb0c30f05.png"> | ![full-screen](https://user-images.githubusercontent.com/89671440/145414451-0c680076-2885-40f6-95eb-b0d137eb9cd2.png) | ![Screenshot 2021-12-09 at 9 46 02 PM](https://user-images.githubusercontent.com/89671440/145414301-5fce54f0-c092-4427-a60b-0098c09840a2.jpg)

randomising seed | generating account
--- | ---
<img width="1353" alt="Screenshot 2021-12-09 at 9 44 59 PM" src="https://user-images.githubusercontent.com/89671440/145414387-8093ae05-602d-416b-b9dd-4e80994a6a29.png"> | <img width="1353" alt="Screenshot 2021-12-09 at 9 45 11 PM" src="https://user-images.githubusercontent.com/89671440/145414334-de92bf80-2c7d-4294-932d-9b03bf272052.png">
 

#### Milestone Description
Updated Design

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 |  Marketing UI (i.e. make it more consumer focused) - ie. add design from Proposal  | https://origami-beta.vercel.app/|
| 2 | Show basic tutorial | https://origami-beta.vercel.app/ |

#### How long do you estimate this milestone will take to complete?
Done. (2 weeks).

#### Project Wallet
baa336bca22c7590256a86c002e4dbe6c1f1c1f6c0a0fd3f0681eecb2cad0787

**Comment by wakawakathedev** [comment]
@manishram - would like to label this as payment request btw -

**Comment by wakawakathedev** [comment]
I could probably fix the mobile view but might do that on the last milestone (and update the selection logic)

*mobile doesn't look great but i'll fix that in the final Milestone

**Comment by tspearing** [comment]
@wakawakathedev, approved as a milestone payout request. Can you create a milestone and link them?

In the doc's it refers to selecting a design, however this doesn't happen. Is this because there's only 1 design right now?
![image](https://user-images.githubusercontent.com/77364430/145514761-f224d0b7-64fb-480c-9add-19870681bf69.png)
 
This design looks awesome, when could we get it?
![image](https://user-images.githubusercontent.com/77364430/145514876-b5e51ec6-397f-44ff-801f-cb1501c61dd0.png)

**Comment by wakawakathedev** [comment]
For the above - I'd like to refactor the design selection (it's currently app) - 
basically accumulated some `tech-debt` when trying to get this out the door.

Selecting isn't available _right now_ but have a few other things to do this week before I can jump back onto this.

I'll include design selection + designs in the final milestone.

>. Can you create a milestone and link them?

@tspearing - what do you mean by this?

**Comment by tspearing** [comment]
@wakawakathedev, we converted this into a milestone payout request. Can you just create a milestone for us to approve and then link them? It can be really simple.

**Comment by wakawakathedev** [comment]
@tspearing like this?
https://github.com/thenewboston-developers/Projects/issues/380

**Comment by tspearing** [comment]
Approved for 5000 TNBC.
