### ISSUE TITLE
Origami - Updated Design - 2

### ISSUE THREAD

**Issue by wakawakathedev** [thenewboston-developers/Project-Proposals#380]
#### Link to original project proposal.
[Proposal](https://github.com/thenewboston-developers/Projects/issues/277)

#### Link to most recent milestone payout request.
[Payout Request](https://github.com/thenewboston-developers/Projects/issues/342)

#### Milestone Description
Updated Design

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 |  Marketing UI (i.e. make it more consumer focused) - ie. add design from Proposal  | https://origami-beta.vercel.app/ |
| 2 | Show basic tutorial | https://origami-beta.vercel.app/ |

#### How long do you estimate this milestone will take to complete?
Done. [Estimate 2 Weeks]

#### Project Wallet
baa336bca22c7590256a86c002e4dbe6c1f1c1f6c0a0fd3f0681eecb2cad0787

**Comment by tspearing** [comment]
Approved.

**Comment by wakawakathedev** [comment]
Closing Milestone as this has been completed.
