### ISSUE TITLE
Status Page - MVP - 1

### ISSUE THREAD

**Issue by wakawakathedev** [thenewboston-developers/Project-Proposals#381]
#### Link to original project proposal.
[Status Page](https://github.com/thenewboston-developers/Projects/issues/363)

#### Link to most recent milestone payout request.
N/A (First Milestone / Payout Request)

#### Milestone Description
MVP

No # | Objective | How can auditors verify milestone?     
--- | --- | --- 
1 | MVP   |  https://github.com/wakawakathedev/thenewboston-status-page 
2 | Deployment  | https://thenewboston-status-page.vercel.app/ 

#### How long do you estimate this milestone will take to complete?
Done.

#### Project Wallet
`2ecd5ebdfff0ace53bb0f171645f912593b2c9eda722548831a4b32221245525`

**Comment by tspearing** [comment]
@wakawakathedev, can you change "TheNewboston" to "thenewboston" or "TheNewBoston"?

Approved for 2500 TNBC.
