### ISSUE TITLE
Status Page - MVP - 1

### ISSUE THREAD

**Issue by wakawakathedev** [thenewboston-developers/Project-Proposals#382]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/381

#### Detailed log of all completed objectives including valid proof of work.
- https://github.com/wakawakathedev/thenewboston-status-page
- https://thenewboston-status-page.vercel.app/

#### Project Wallet
`2ecd5ebdfff0ace53bb0f171645f912593b2c9eda722548831a4b32221245525`

**Comment by tspearing** [comment]
Closing as #382 is considered a milestone payout request.
