### ISSUE TITLE
TNB Gifts - Front-End and Hosting - MILESTONE_2

### ISSUE THREAD

**Issue by picko1990** [thenewboston-developers/Project-Proposals#387]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/291

#### Detailed log of all completed objectives including valid proof of work.
https://picko1990.pythonanywhere.com/

#### Project Wallet
b0b0b98f9bd0b9809ac30706363ccfe7294fc5dc06eec9fb916bb17e8d91536e

**Comment by manishram** [comment]
Approved for 25k TNBC.

**Comment by manishram** [comment]
Approved for 25k TNBC
