### ISSUE TITLE
Blockchain Explorer - Milestone - 2 

### ISSUE THREAD

**Issue by itsnikhil** [thenewboston-developers/Project-Proposals#388]
# [Openblockchain Explorer](https://github.com/open-blockchain-explorer)

https://github.com/thenewboston-developers/Projects/issues/23

### Tasks:
- Charts and graphs - Add charts related to tnbcrow stats API, Time range silder and remove data points
- Search functionality - Search for transactions by account number 
- Bulk payments - Create shareable payment request link, Keysign integration and download bulk payment receipt on successful payment
- Testnet - Deploy and Integrate explorer with testnet as well
- Frontend UI changes and Improvements 
- Designs - Beta pages designs. Like government and locked coins page
- Backend APIs and Data - CSV to JSON to update analytics
- Sort and filter transactions for an account
- Responsive - Mobile optimizations
- Bug fixes - and more

### Proof and links for evaluation:
BACKEND
  - https://github.com/open-blockchain-explorer/Bank/pull/2
  - https://github.com/open-blockchain-explorer/Bank/pull/3
  - https://github.com/open-blockchain-explorer/Bank/pull/4
  - https://github.com/open-blockchain-explorer/Bank/pull/9
  - https://github.com/open-blockchain-explorer/tnbexplorer/issues/34
  - https://github.com/open-blockchain-explorer/tnbexplorer/issues/35
  - https://github.com/open-blockchain-explorer/tnbexplorer/issues/70
  
FRONTEND
  - https://github.com/open-blockchain-explorer/tnbexplorer/pull/21
  - https://github.com/open-blockchain-explorer/tnbexplorer/pull/25
  - https://github.com/open-blockchain-explorer/tnbexplorer/pull/45
  - https://github.com/open-blockchain-explorer/tnbexplorer/pull/55
  - https://github.com/open-blockchain-explorer/tnbexplorer/pull/48
  - https://github.com/open-blockchain-explorer/tnbexplorer/pull/50
  - https://github.com/open-blockchain-explorer/tnbexplorer/issues/33
  - https://github.com/open-blockchain-explorer/tnbexplorer/issues/37
  - https://github.com/open-blockchain-explorer/tnbexplorer/pull/26
  - https://github.com/open-blockchain-explorer/tnbexplorer/pull/44
  - https://github.com/open-blockchain-explorer/tnbexplorer/pull/49
  - https://github.com/open-blockchain-explorer/tnbexplorer/pull/27
  - https://github.com/open-blockchain-explorer/tnbexplorer/pull/57
  - https://github.com/open-blockchain-explorer/tnbexplorer/pull/42
  - https://github.com/open-blockchain-explorer/tnbexplorer/pull/43
  - https://github.com/open-blockchain-explorer/tnbexplorer/pull/75
  - https://github.com/open-blockchain-explorer/tnbexplorer/pull/71
  - https://github.com/open-blockchain-explorer/tnbexplorer/pull/72
  - https://github.com/open-blockchain-explorer/tnbexplorer/pull/79
  - https://github.com/open-blockchain-explorer/tnbexplorer/issues/82
  - https://github.com/open-blockchain-explorer/tnbexplorer/pull/86

|Objective|Coins|
|-|-|
|Stats and charts improvements and tnbCrow integration|80000|
|Keysign integration and bulk payment request|100000|
|TNBAnalysis and TNBFaucet to TNBExplorer migration|100000|
|Backend APIs for stats and CSV to JSON changes|120000|
|Sort and filter of transactions, mobile optimizations and other UI enhancements|50000|
|Testnet setup and integration with Explorer|60000|
|Management|20000|
|**TOTAL**|**530000**|

### Project wallet address
1dfb0e7dd672032da0d8c29385ba6d22ec9d1134a115cc5596c5e4b69e6fc9a5

**Comment by tspearing** [comment]
@itsnikhil, please create a milestone first and link to this payout request. 

We expect this will be 120k TNBC.

**Comment by itsnikhil** [comment]
Curious to know how you landed on 120k.
We completey eliminated TNB Analysis and Faucet, Integrated with 2 third party services (tnbcrow and keysign). Many more stuff and 120k is too less.

**Comment by tspearing** [comment]
@itsnikhil our front end and back end engineers looked into this and 120k was their conclusion.

**Comment by itsnikhil** [comment]
@tspearing it took 3 people close to 4 months to complete this milestone and 120k is very less according to all the things which we have done.
To give you some context on migration there was earlier it was django forms direct integration without any external APIs but since we have to integrate this with TNBExplorer to had to create APIs, add recaptacha, etc. And, for all the UI related stuff I did not ask for UI design related costs.
This steals all the motivation to submit for 3rd milestone.

**Comment by Kycermann** [comment]
Hi @itsnikhil, we've evaluated this milestone at 120k TNBC. I know this isn't what you want to hear. The amount is based on assessments from individuals across the Audit, Backend and Frontend teams. Let us know here if you're willing to accept this payout.

**Comment by itsnikhil** [comment]
@Kycermann I am not in this for money but I have a team to pay too. This is unacceptable and I am very sorry. Should I close this issue?

**Comment by Kycermann** [comment]
> @Kycermann I am not in this for money but I have a team to pay too. This is unacceptable and I am very sorry. Should I close this issue?

You're welcome to accept the payment or close the issue [and not accept the payment]. I've given you all the info I could, though, so I won't be replying to this issue again.

**Comment by manishram** [comment]
Hey @itsnikhil we are going to re-evaluate the milestone.

**Comment by itsnikhil** [comment]
Thanks @manishram

**Comment by manishram** [comment]
Hey @itsnikhil, we re-evaluated the milestone and the amount came to be the same that is 120k TNBC.

**Comment by itsnikhil** [comment]
@manishram even though I am not happy at all with your valuation but I don't want my team to suffer. I have no choice but to accept this and use my own funds to cover up other expenses.
