### ISSUE TITLE
Mobile Wallet - MVP - 1

### ISSUE THREAD

**Issue by Kycermann** [thenewboston-developers/Project-Proposals#398]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/362

#### Detailed log of all completed objectives including valid proof of work.

https://cdn.discordapp.com/attachments/914674865309642776/914685672089075812/TheNewBoston_Mobile_Wallet_Demo.mov

https://github.com/Kycermann/TNB-Wallet

#### Project Wallet
f1decb80339a4bb6c089b77cbac553e23a6ca86b0cfc64adb8c8eb8f8b57d815

**Comment by manishram** [comment]
Approved for 200k TNBC
