### ISSUE TITLE
TNB Apparel and Accessories - MVP

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Project-Proposals#399]
#### Link to the milestone and objectives table.
[#391](https://github.com/thenewboston-developers/Projects/issues/391)

#### Detailed log of all completed objectives including valid proof of work.
- Fully functional website: https://getmefunky.com
- One can buy items with TNBC 

#### Project Wallet
583d44329e11c2b3b996a5bce882858b3087d723fe0e4fb4aab6e4402238c594

**Comment by Kycermann** [comment]
Approved for 70k TNBC.

**Comment by buckyroberts** [comment]
First website where people are able to buy physical goods for TNBC :-) Also a great way of getting the word out about thenewboston. Awesome idea!

Approved for 250k TNBC.
