### ISSUE TITLE
Introducing TNBC to Arabic Audience - MVP

### ISSUE THREAD

**Issue by hayderkharrufa** [thenewboston-developers/Project-Proposals#400]
#### Link to the milestone and objectives table.
[#385](https://github.com/thenewboston-developers/Projects/issues/385)

#### Detailed log of all completed objectives including valid proof of work.
| # | Objective             | How can auditors verify milestone?     | Proof|
| - | --------------------- | -------------------------------------- |--------
| 1 | Make the video | I will provide a link to the video and translate the parts where I mention TNBC to English | [Translated Video](https://www.youtube.com/watch?v=R--Ji8g5PZw) <br><br>Enable English subtitles and watch from 3:02 to 3:57
| 2 | Publish on my [Facebook page](https://www.facebook.com/iAmHaydara) | I will provide a link | [Video](https://www.facebook.com/iAmHaydara/videos/342336567727730/)
| 3 | Publish on my [YouTube channel](https://www.youtube.com/haydara) |  I will provide a link |[Video](https://www.youtube.com/watch?v=R--Ji8g5PZw)
| 4 | Publish on my [Instagram page](https://www.instagram.com/iamhaydara/) | I will provide a link |[Video](https://www.instagram.com/tv/CYRk3ZBoNU7/?utm_source=ig_web_copy_link)
| 5 | Host Jumpy Coin contest in the #random channel on TNB Discord server | I will provide a link | [Discord Message 1](https://discord.com/channels/774574985510518806/900990695886684221/925878108312174672)<br>[Discord Message 2](https://discord.com/channels/774574985510518806/774920983021748235/929166309831356426)
| 6 | Post photos promoting TNB and Jumpy Coin on my [Instagram meme page](https://www.instagram.com/nokat.barmaja/) | I will provide a link | [Post Link](https://shorturl.at/chxN7)
| 7 | Post photos promoting TNB and Jumpy Coin on my [Facebook meme page](https://www.facebook.com/nokat.barmaja)| I will provide a link | [Post Link](https://www.facebook.com/nokat.barmaja/posts/442012044310150)

[Jumpy Coin](https://play.google.com/store/apps/details?id=org.iamhaydara.jumpycoin) has 100+ installs now on Play Store.

#### Project Wallet
7a42c9cfc4d0f0d2ba5fe126a712f5bbe8ce20d002d427b48f7490b074b9f361

**Comment by manishram** [comment]
Hey @hayderkharrufa we are taking a little bit more time to see how this milestone is performing. We'll update you soon.

**Comment by manishram** [comment]
Approved for 12500 TNBC
