### ISSUE TITLE
TNB Discord Security - First and final - 01

### ISSUE THREAD

**Issue by avinashupadhya99** [thenewboston-developers/Project-Proposals#403]
#### Link to the milestone and objectives table.
#231 

#### Detailed log of all completed objectives including valid proof of work.

| # | Objective | How can auditors verify milestone?
| -- | -- | --
| 1 | Scan all Discord messages | [See the code](https://github.com/avinashupadhya99/TNB-Discord-Security/blob/c74bea934ca98f54f769a062c8713ebc32a2d1e3/src/index.ts#L35)
| 2 | Detect TNB signing keys in Discord messages (since account numbers are the same format as signing keys, they will be treated like signing keys) | The bot will send a message ![image](https://user-images.githubusercontent.com/52544819/149632160-3748cee5-fa15-4c39-ad6b-450e9702cfe1.png)
| 3 | If the balance is 0 it could be an account number, so don't process it | Paste an account number into chat
| 4 | If the balance is enough to withdraw more than 3 TNB (so 6 or above), then proceed to withdraw |  [See the code](https://github.com/avinashupadhya99/TNB-Discord-Security/blob/c74bea934ca98f54f769a062c8713ebc32a2d1e3/src/account.ts#L18)
| 5 | DM the user with their new signing key, and if they have DMs disabled, mention them in a channel asking to enable DMs and use /recover_compromised_wallets | Try the command ![image](https://user-images.githubusercontent.com/52544819/149633139-9ebcea76-c10f-43c2-ae0a-dba76df25592.png) DM- ![image](https://user-images.githubusercontent.com/52544819/149632946-d0c42bf9-2d80-45d0-8c4c-1499325ce647.png) In case of not being able to reach the user through DM - ![image](https://user-images.githubusercontent.com/52544819/149633192-e8a8b2d4-b23e-416a-ba49-431efe3c740b.png)
| 6 | /recover_compromised_wallets | DM the user with their new signing key and delete the new signing key from the bot's database [See code for deleting signing key](https://github.com/avinashupadhya99/TNB-Discord-Security/blob/c74bea934ca98f54f769a062c8713ebc32a2d1e3/src/commands/recover_compromised_wallets.ts#L40) DM - ![image](https://user-images.githubusercontent.com/52544819/149632233-7d4f106b-303e-4e62-b258-e3d7a2fcde64.png)
| 7 | If a user pastes a signing key or something that could be parsed as a signing key but doesn't have a balance, warn them not to paste signing keys | Paste an account number for instance ![image](https://user-images.githubusercontent.com/52544819/149632874-f5afffa1-3a9a-44b8-80bc-542487c9ec0c.png)

#### Source code
https://github.com/avinashupadhya99/TNB-Discord-Security

#### Invite link
https://discord.com/api/oauth2/authorize?client_id=856487010712682537&permissions=0&scope=bot%20applications.commands
**(Currently setup with the testnet)**

#### Project Wallet
`22d0f0047b572a6acb6615f7aae646b0b96ddc58bfd54ed2775f885baeba3d6a`

**Comment by Kycermann** [comment]
A lot of those messages should probably be ephemeral or only accessible in DMs. Could you confirm that this is the case for /recover_compromised_wallets?

**Comment by Kycermann** [comment]
PS: This is awesome!

**Comment by Kycermann** [comment]
Hi @avinashupadhya99, it doesn't seem to work for me! I pasted a signing key (nothing else in the message) with a balance above 6, got the warning, but it didn't transfer the coins and no new signing key in the `/recover_compromised_wallets`. Really excited about this project though!

**Comment by avinashupadhya99** [comment]
Hi @Kycermann , yes the `/recover_compromised_wallets` command is ephemeral.
The bot is hooked up to the testnet, did you try it with a testnet account?

**Comment by manishram** [comment]
Approved 15k TNBC
