### ISSUE TITLE
SwiftChow 

### ISSUE THREAD

**Issue by Sulaiman001** [thenewboston-developers/Project-Proposals#404]
# Project Details
SwiftChow A Multi Restaurant/Store Food and Grocery Ordering Platform 

#### How would you describe your project?
SwiftChow will be a multi restaurant food ordering platform where users will be able to order food from different restaurant that are available on the application. They will be able to pay using TNBC and some other selected cryptocurrency. 

#### What problem does this project solve?
Presently most of the food ordering application out there does not support payment with cryptocurrency, these will be the first of its kind to do so.

#### Who is the target market?
The target market generally is everyday user but to be specific crypto enthusiast and as the adaptation of cryptocurrency grows we get to be noticed by more people.

#### How will this project benefit the network and/or the community?
I guess almost everybody in the crypto space remember the story of the Bitcoin pizza guy, the dude that wanted to buy pizza with bitcoin and had to post on reddit waited for days for someone to be interested in his offer and had to wait another few days for him to get hands on his pizza. One can only imagine how he felt about the difficulty of spending his hard earned bitcoin, presently now I know it is very easy to order food or do grocery online but when it comes to payment on this platforms we the crypto users does not come to mind and because of that we still have to convert our crypto to fiat before we can spend it but with SwiftChow that should not be the case anymore. 

#### How is this project centered around thenewboston?
The project will be using TNBC as the primary inapp payment method with option for other selected cryptocurrency and fiat(card paymeny) option enabled as well so as not to be rejected by the major app stores. 

#### What is the estimated completion date for this project? (rough estimates are acceptable)
4 Months 

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
https://docs.google.com/document/d/1k4JsFQK0177HvJfHfmewzmOPb_IgGTJE-reMc7lADQk/edit?usp=sharing

#### What is your Discord username?
DISCORD USERNAME HERE (https://discord.gg/thenewboston)
sulaiman#3809

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)
- OPTIONAL ATTACHMENT HERE
- OPTIONAL ATTACHMENT HERE
- OPTIONAL ATTACHMENT HERE

# Milestone 1 - Minimum Viable Product (MVP) Details

Please include a detailed breakdown of the MVP including a list of all quantifiable objectives. Upon 
completion of the MVP, each objective will be reviewed by thenewboston team and once all objectives have been 
verified as completed, amount of coins will be negotiated. 

Note that all future detailed milestone breakdowns will be written as a separate GitHub issue. Only the first 
milestone which is for MVP is included in this project proposal.

---

#### MVP Description
SHORT DESCRIPTION OF MVP HERE

#### Objectives for MVP

| # | Objective             | How can auditors verify milestone?    			|
| - | --------------------- | ----------------------------------------------------------|
| 1 | UI/UX		    | General UI/UX of complete application   			|
| 2 | Frontend              | Implementation of all frontend features as shown in UI/UX |
| 3 | User 	            | Users should be able to register and get verified		|
| 4 | Store Owner/Vendor    | Store Owners/ Vendor should be able to create account and users can upgrade to Vendor. |

#### How long do you estimate for the MVP to complete?
3 Weeks

#### Project Wallet
8e33eab8d207c8c54b2437f22e318be43bd247013898b3f03c3d58bc16ae0717

**Comment by manishram** [comment]
The project lead is going to work on PayUtil project for now. Closing this.
