### ISSUE TITLE
decentralized escrow

### ISSUE THREAD

**Issue by picko1990** [thenewboston-developers/Project-Proposals#407]
# Project Details

#### How would you describe your project?
A decentralized escrow to store and secure coins without the need of a 3rd party to hold the coins
Users can use this to safely exchange different things, like goods, freelance services... etc

#### What problem does this project solve?
People need to exchange goods and services, but they can't always trust each other, thus the need for a decentralized escrow

#### Who is the target market?
Every TNBC user who needs to exchange a service where trust is needed

#### How will this project benefit the network and/or the community?
It will make it safer to exchange goods and services

#### How is this project centered around thenewboston?
In everyway

#### What is the estimated completion date for this project? (rough estimates are acceptable)
1.5 months

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
Milestone 1 - Basic MPV with the escrow functionality working for 2/2 parties

#### What is your Discord username?
picko1990#6172

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)

# Milestone 1 - Minimum Viable Product (MVP) Details

#### MVP Description
Escrow functionality will be working for 2/2 parties, where the coins will be escrowed in an account which no one owns the signing key for
Coins will be released from escrow to the destination account, where both parties give the signal to release the coins

#### Objectives for MVP

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 | Decentralized Escrow MPV | It will be hosted online, they can visit the website and test |

#### How long do you estimate for the MVP to complete?
20 Days

#### Project Wallet
b0b0b98f9bd0b9809ac30706363ccfe7294fc5dc06eec9fb916bb17e8d91536e

**Comment by manishram** [comment]
Hey @picko1990 
> Escrow functionality will be working for 2/2 parties, where the coins will be escrowed in an account which no one owns the signing key for

When you say no one owns the signin key, does that mean none of the 2 parties or it means not even by the escrow will own it? 
If the answer is "escrow will own the signin key" then how this is decentralized?

**Comment by picko1990** [comment]
Technically it will be owned by both parties at the same time.
The escrow won't own the signing key, nor store any data

**Comment by Kycermann** [comment]
Hi, it isn't clear to us how payments could be reversed by a third party (escrow) if this project is decentralised.

**Comment by picko1990** [comment]
@Kycermann Let me know if you're available for a call and I'll explain to you
