### ISSUE TITLE
The Ad Network 

### ISSUE THREAD

**Issue by Sulaiman001** [thenewboston-developers/Project-Proposals#408]
# Project Details

#### How would you describe your project?
Reference to Project Idea https://github.com/thenewboston-developers/Projects/issues/146
Develop an ad network that accepts TheNewBostonCoins (TNBC) along with other mainstream cryptocurrencies like bitcoin etc.

#### What problem does this project solve?
Enabling advertisers to create ad campaigns and pay with Cryptocurrency.
Enable Publishers to monetise there websites with ads and get paid in cryptocurrency.

#### Who is the target market?
Cryptocurrency enthusiast, advertisers and publishers alike.

#### How will this project benefit the network and/or the community?
The project will increase TNBC marketability and enhance the possibility of establishing and accepting crypto-currency globally.

#### How is this project centered around thenewboston?
The platform will provide options for Advertisers to pay using TNBC creating avenue for TNBC spending while Publishers will get their payment in TNBC as well.

#### What is the estimated completion date for this project? (rough estimates are acceptable)
5 Months

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
ANSWER HERE

#### What is your Discord username?
sulaiman#3809

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)
- OPTIONAL ATTACHMENT HERE
- OPTIONAL ATTACHMENT HERE
- OPTIONAL ATTACHMENT HERE

# Milestone 1 - Minimum Viable Product (MVP) Details

Please include a detailed breakdown of the MVP including a list of all quantifiable objectives. Upon 
completion of the MVP, each objective will be reviewed by thenewboston team and once all objectives have been 
verified as completed, amount of coins will be negotiated. 

Note that all future detailed milestone breakdowns will be written as a separate GitHub issue. Only the first 
milestone which is for MVP is included in this project proposal.

---

#### MVP Description
SHORT DESCRIPTION OF MVP HERE

#### Objectives for MVP

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 | Website | Users should be able to register as either advertisers or publishers|
| 2 | Website Dashboard | TNBC Payment integration for advertisers and site management for publishers |

#### How long do you estimate for the MVP to complete?
3 Weeks

#### Project Wallet
8e33eab8d207c8c54b2437f22e318be43bd247013898b3f03c3d58bc16ae0717

**Comment by manishram** [comment]
The project lead is going to work on PayUtil project for now. Closing this.
