### ISSUE TITLE
TNBGem - All about banks:1 - 2

### ISSUE THREAD

**Issue by avinashupadhya99** [thenewboston-developers/Project-Proposals#411]
#### Link to the milestone and objectives table.
#310 

#### Detailed log of all completed objectives including valid proof of work.
| # | Objective | How can auditors verify milestone? |
| - | --------------------- | -------------------------------------- |
| 1 | createBank | [Check code in Github](https://github.com/avinashupadhya99/TNBGem/blob/048c34fef458db71c780b71cba8bd0634164a536/lib/thenewboston/bank.rb#L5) and verify using the network |
| 2 | getConfig | [Check code in Github](https://github.com/avinashupadhya99/TNBGem/blob/048c34fef458db71c780b71cba8bd0634164a536/lib/thenewboston/bank.rb#L22) and verify using the network |
| 3 | updateTrust | [Check code in Github](https://github.com/avinashupadhya99/TNBGem/blob/048c34fef458db71c780b71cba8bd0634164a536/lib/thenewboston/bank.rb#L30) and verify using the network |
| 4 | getAccounts | [Check code in Github](https://github.com/avinashupadhya99/TNBGem/blob/048c34fef458db71c780b71cba8bd0634164a536/lib/thenewboston/bank.rb#L18) and verify using the network |
| 5 | updateAccountTrust | [Check code in Github](https://github.com/avinashupadhya99/TNBGem/blob/048c34fef458db71c780b71cba8bd0634164a536/lib/thenewboston/bank.rb#L26) and verify using the network |
| 4 | getTransactions | [Check code in Github](https://github.com/avinashupadhya99/TNBGem/blob/048c34fef458db71c780b71cba8bd0634164a536/lib/thenewboston/bank.rb#L6) and verify using the network |
| 4 | Tests | Run the [test command in the repo](https://github.com/avinashupadhya99/TNBGem/blob/048c34fef458db71c780b71cba8bd0634164a536/test/bank_test.rb)  and [see if it passes](https://github.com/avinashupadhya99/TNBGem/runs/4908551245?check_suite_focus=true#step:4:59) |
| 5 | Documentation | [Read the docs](avinashupadhya99.github.io/tnbgem/bank) |

#### Project Wallet
`94cf53921e9c5ddf48dc5589b7cdf111f7acdc93dc3073b94880416d4676b9ae`

**Comment by manishram** [comment]
Approved for 50k TNBC
