### ISSUE TITLE
Bitty - Fight Engine - 3

### ISSUE THREAD

**Issue by Kycermann** [thenewboston-developers/Project-Proposals#414]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/413

#### Detailed log of all completed objectives including valid proof of work.
https://github.com/thenewboston-developers/Projects/issues/413

#### Project Wallet
c79d631ccfe446e0a92af30afd2fac318e7eeedc4efb2bf58f0ff259c384496d

**Comment by manishram** [comment]
Approved for 110k
