### ISSUE TITLE
tnbcfundme.co.za- MILESTONE01 - 01

### ISSUE THREAD

**Issue by lwazi4787** [thenewboston-developers/Project-Proposals#415]
#### Link to the milestone and objectives table.
#314

#### Detailed log of all completed objectives including valid proof of work.
completed the first mvp, I used the keysign extension for payments. the link is below.

https://tnbcfundme.co.za/signup.php

#### Project Wallet
158fa206324ca39e0b5b3156f96f243d2233545ef9b4b2dea1fae8aee258c9cf

**Comment by manishram** [comment]
Hey @lwazi4787 should we close https://github.com/thenewboston-developers/Projects/issues/386 ?

**Comment by lwazi4787** [comment]
@manishram yes u can close it.

**Comment by lwazi4787** [comment]
@manishram the link I provided above just got suspended (I don't want to keep paying for it since I'm not really live yet).... U can use the link below for now... Please use it on a desktop for now I've been trying to use on my mobile device... The 000webhost servers are not allowing it.

https://tnbcfundme.000webhostapp.com/

**Comment by lwazi4787** [comment]
@manishram while the first milestone is being reviewed... Can I submit request for second milestone?

**Comment by manishram** [comment]
Hey @lwazi4787, yes you can.

**Comment by manishram** [comment]
Hey @lwazi4787,
1. The signin and signup page is having password with input type text instead of password
![image](https://user-images.githubusercontent.com/22790904/153756902-e52e1f51-b7b1-498a-b15b-1a9d1c7cdab6.png)

2. On clicking **home** from the navigation menu it takes me to the home page and then I need to login back. Is that how it was supposed to be?

**Comment by lwazi4787** [comment]
1. I had a typo on the input type... I spelled password wrong... But it has been fixed.
2. The home  page link thing was intensional, but it doesn't really log you out. I think what I will do is when you signed in and you decide to go to the home page... Instead of showing "sign in" I'll show dashboard or "user area", and it will link back to the posts.

**Comment by lwazi4787** [comment]
Hey @manishram I got your response on the above post.

**Comment by lwazi4787** [comment]
@manishram I just uploaded updates for your second question... U can check them out.

**Comment by lwazi4787** [comment]
Hi @manishram... Was just checking where were u with the review?... Since you have been reviewing for over 2 weeks now.

**Comment by manishram** [comment]
Approved for 5000 TNBC.
