### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by EvolOfThings** [thenewboston-developers/Project-Proposals#5]
#### How would you describe your project?
**A physical asset sharing app.**

> An asset can be a book, electronic gadgets, even furniture, and/or anything that's physical. A platform where people can lend the assets that they no longer use, but would want other folks to make use of it. The accountability factor plays a major role and hence it fits right into the blockchain philosophy. We would be able to see who had used it before us, and what condition it is in at the time of "checkout", and even reviews by previous borrowers of that asset. This would build a trusted community where people can borrow and lend the stuff they longer use and want to use respectively.

#### What problem does it solve?

> It can help people find something that they want to use at no cost( or at a very less fee).

#### Who is the target market?

> Anyone who wants to lend or borrow any physical asset rather than unnecessarily buying a new product.

#### What do you think is the opportunity of this project?

> It could change the way people buy/borrow/lend things. Rather than buying, more people would want to share the assets that they no longer use personally, meanwhile, they can earn for lending their assets.

#### How does it integrate with thenewboston digital currency work?

> Not planning to use TNB digital currency for the actual transactions(however, I'm open to hearing out ideas), rather it's better to use fiat currency as the mode of payment(tip to the owners of an asset.

#### Are there any competitors?

> No.

#### Will you need specific information or advice?

> No. However, would need help from senior devs and designers to build this.

#### What are your goals and objectives?

> To get the MVP out as soon as possible, with minimalistic UI design to start with.

#### How will you evaluate project success?

> The number of users signing up for borrowing or lending an asset. 

#### What risks should you plan to manage?

> Losing a borrowed asset - still in the process of figuring it out.

#### How many total coins are you requesting?

> Not quite sure.

GitHub usernames and roles of all team members:

> - EvolOfThings(Rishad) - Project Lead and Developer.
> (Looking for teammates)

**Comment by manishram** [comment]
Hey @EvolOfThings , please provide details regarding what skills you are looking for in your teammates so people can understand if they fit into the project or not.

**Comment by praveenHp** [comment]
Hey, I liked the idea. I think this serves the best for selling second hand goods too on platforms like olx, craiglist too. 

I have a question though, how would you attach the physical entity to the virtual one? For ex: I might have a sofa which I wish to sell or give for borrowing, how can the borrower know the sofa that is  being handed over physically is as same as the one that's shown in your app.
