### ISSUE TITLE
Diddy

### ISSUE THREAD

**Issue by Mirch** [thenewboston-developers/Project-Proposals#56]
#### How would you describe your project?
Diddy is a mobile application that offers multiple tools for tracking your progress in a certain area (e.g., learning a new skill). It's all based on the idea that you need 10,000 hours of doing something to master it, so that will be the main focus of the app - letting users track the time they worked on their goal. Additionally, it will allow users to set specific sub-goals and deadlines. 
To keep people motivated and educate them on how to progress, several articles will be available for reading in the application.

#### What problem does it solve?
It solves the issue of tracking how much time you've worked on a specific goal or skill - such as playing guitar. You can, for example, start the timer when you start practicing and stop it at the end of your session. You can also set goals such as "I want to learn to play these songs by the end of the month".

#### Who is the target market?
People who want to master a skill and to organize their time as well as possible in order to make their learning process optimal.

#### What do you think is the opportunity of this project?
There are many low-quality apps that try to solve this problem, but it seems that none of them offer the whole package that a user would need. Also, it would introduce a new segment of people to thenewboston's currency.

#### How does it integrate with thenewboston digital currency work?
The app will offer subscriptions that users will be able to buy using TNB.

#### Are there any competitors?
As mentioned before, there are many apps that are based on the 10,000 hours idea; additionally, any time management app could be viewed as a competitor.

#### Will you need specific information or advice?
Probably, when integrating with the payment system. But not right now.

#### What are your goals and objectives?
- Help people achieve their goals and track their progress
- Offer high quality content about achieving their goals
- Introduce thenewboston to more people

#### How will you evaluate project success?
- Number of users tracking their progress on a daily/weekly basis
- Number of users upgrading to a paid subscription

#### What risks should you plan to manage?
- The infrastructure not being scalable
- The product not being appealing to the target market
- The target market not knowing about the product

#### What are your milestones?
- Milestone 1 : Hiring and setting up 
- Milestone 2 : Design and validation
- Milestone 3: MVP implementation
- Milestone >4: New vertical slices to improve and enrich the application  

#### Tell us about your team members:
Full Name, Slack Username, GitHub Username, LinkedIn, Role, Team Joining Date, Team Leaving Date, Account number
Mircea Teodor Oprea, Mircea Teodor Oprea, Mirch, mircea-oprea, Project Manager, 04.01.2021, -, dc3eb7a93238a4e691817d294c97fa372748807c473130901b71b819032a2faa

#### List the roles of any additional team members you would be looking for?
- Designer 
- Mobile developer (Flutter, React Native or Xamarin)
- Backend developer (.NET Core or Python)

**Comment by manishram** [comment]
Hey @Mirch I liked your proposal. Next you need to comment down here the project repository link. You can provide blank repo link as well if you have not started working on the project yet.

**Comment by Mirch** [comment]
https://github.com/DiddyApp/diddy-mobile here it is

**Comment by manishram** [comment]
Hey, @Mirch your project has been added to the repository.
**Diddy:** https://github.com/thenewboston-developers/Project-Proposals/tree/master/projects/56-Diddy
