### ISSUE TITLE
Keysign - Project Proposal

### ISSUE THREAD

**Issue by mrbusysky** [thenewboston-developers/Project-Proposals#6]
#### How would you describe your project?
Chrome/firefox extension for transaction signing.

#### What problem does it solve?
Decentralized interaction with the chain from browser

#### Who is the target market?
Everyone and Site operators

#### What do you think is the opportunity of this project?
To allow decentralized logins and communication to the chain from the browser.

#### How does it integrate with thenewboston digital currency work?
Partnering with the thenewboston-js team for API features. Creating a handshake between sites and the browser that allows them to connect to the chain.

#### Are there any competitors?
As of now? Not that I know of.

#### Will, you need specific information or advice?
Yes, I will need to work with the TNB JS API team to build out the documentation and API's to make the browser extension have more features.

#### What are your goals and objectives?
Wide-scale adoption of the currency and to keep it decentralized.

#### How will you evaluate project success?
By seeing wide adoption from online services and users.

#### What risks should you plan to manage?
Honestly, there isn’t much risk. It’s a decentralized application. It all depends on how the community takes the app and uses it. But from what I have seen from most chains that have browser plugins. Having something like this makes adoption a lot easier.
 
#### Milestones?
- Scope
- Design: Both Firefox and Chome plugin designs
- Feature - Secure wallet login/creation
- Feature - Key Storage
- Feature - Wallet creation
- Feature - Public servers, Coin sending
- Feature - Secure handshake for websites
- More - Depends on API's

GitHub usernames and roles of all team members:
- mrbusysky - Lead Developer/Lead Design
- More: I'm willing to bring on others

#### Extra information:

**Feature set:**
- Store an unlimited number of account keys, encrypted with AES
- Api to allow public/private key matches to allow for a decentralized login system.
- Api to allow fast coin sending via the browser from just the click of buttons.
- Wallet creation
- List of public servers to sign transactions with.
- And much more

**Example:**
**Decentralized login:**
Browser handshake: calls to chrome or firefox extension 
If private key matches public key send true if valid send confirmation

**Slack**
MrSky - already messaged Manish

**More details on the project to show I have it scoped out.**
![Screenshot_2020-11-15 mrbusysky keysign](https://user-images.githubusercontent.com/58412572/99715223-67fdaa00-2a5b-11eb-925e-e9317f86c544.png)

**Comment by manishram** [comment]
Hey, @mrbusysky we replaced the field How many total coins are you requesting? with project milestones. So please update your proposal. Please add your slack name as well so we can contact you if required. Also, update the title of the proposal with your project name.

**Comment by Chrisha1212** [comment]
Hi @mrbusysky Do you have specification how many Team you would like to join in to this project and what are the requirement and qualifications?

**Comment by manishram** [comment]
Congratulations @mrbusysky, we liked your project proposal. Now you need to provide your project repository link (You can comment down here). You can provide an empty repository link also if you have not started working on your project yet.

**Comment by mrbusysky** [comment]
> 
> 
> Hi @mrbusysky Do you have specification how many Team you would like to join in to this project and what are the requirements and qualifications?

Honestly, i don't really need teammates. But I'm open to finding some even if it's on my own.

**Comment by mrbusysky** [comment]
> 
> 
> Congratulations @mrbusysky, we liked your project proposal. Now you need to provide your project repository link (You can comment down here). You can provide an empty repository link also if you have not started working on your project yet.

https://github.com/mrbusysky/keysign

**Comment by Chrisha1212** [comment]
Congratulations @mrbusysky !! I understand but incase you will need some Team mates just let me know.

**Comment by manishram** [comment]
@mrbusysky , your project has been added to https://github.com/thenewboston-developers/Project-Proposals/tree/master/projects/6-Keysign.
