### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by arjunraghurama** [thenewboston-developers/Project-Proposals#7]
#### How would you describe your project?
"Educate.me" An online learning platform based on [IPFS](https://ipfs.io/) technology where in the e-learner get to learn at free of cost.
Online leaning is becoming a norm because of the pandemic. Most of the platforms that offer the courses are very expensive.
This should not stop someone from leaning. So through this proposed project we would like to make education accessible to
everyone at no cost.

#### What problem does it solve?
Here we are trying to make education available to every individual at free of cost.

#### Who is the target market?
Every individual who is into E-learning.

#### What do you think is the opportunity of this project?
With this proposed project we can get a user base who are learning through the platform and are users of thenewboston currency.

#### How does it integrate with thenewboston digital currency work?
We are planning to incentivize the tutors with the thenewboston currency.
Also the e-learner who seeding(IPFS will be used here) the file will be rewarded with the thenewboston currency.

#### Are there any competitors?
Yes. There are a lot of e-learning sites but they do come at a cost. Since here the learning is for free we can 
get the userbase.

#### Will you need specific information or advice?
Yes if the proposal gets accpeted.

#### What are your goals and objectives?
Free education for everyone. ( In doing so get a user base for the thenewboston currency).

#### How will you evaluate project success?
Based on the number of people who gets be

#### What risks should you plan to manage?
-> Getting the userbase

#### How many total coins are you requesting?
[TBD]

GitHub usernames and roles of all team members:
[Team needs to be formed yet]

**Comment by manishram** [comment]
Hey @arjunraghurama please change your proposal title with the name of your project. And please check new template for project proposal where you will see we replaced number of coins with your milestones because most of the people are not sure about how much coins they should request.
