### ISSUE TITLE
Project Proposal - Digital Invoice

### ISSUE THREAD

**Issue by prajwalkulkarni** [thenewboston-developers/Project-Proposals#9]
#### How would you describe your project?
[My project idea is to create a system where people can receive invoices digitally. An app that can be considered as a central repository to receive/keep invoices also aims to improve the user's shopping experience by providing loyalty points and discounts on receiving a digital invoice. ]

#### What problem does it solve?
[The idea is mainly concerned with the environment and climate change, shifting from paper invoices to digital invoices would prevent the felling of the trees by a large number. But also, it'd reduce the pupil's burden of carrying a printed invoice for proof/ verification or whatsoever. ]

#### Who is the target market?
[Any medium to large scale businesses selling/reselling products/goods. Initially, planning to start with restaurants, retailers, and further planning to expand it to other industries as well.]

#### What do you think is the opportunity of this project?
[The opportunity here is to digitalize proof of payment, have a positive environmental impact, help users with their financial management(by monitoring their expenditures) and also help businesses keep a track of their sales and drive more customers by offering exclusive discounts and so forth.  ]

#### How does it integrate with thenewboston digital currency work?
[As described in the comments section, I'm planning to integrate thenewboston currency in further stages, like offering special offers for payments done with thenewboston digital currency and also enable in-app payment to pay with thenewboston currency for fast and secure payments and other Interesting features which would make use of thenewboston currency, this would encourage customers to switch to using thenewboston currency over conventional payments like physical cash or other digital payments like Paypal. If it comes out well, there's also a possibility to completely pivot towards using thenewboston currency for all the transactions.]

#### Are there any competitors?
[This project is a combination of POS and digital invoice system. For, only POS there are already many companies, firms soaring high. But, as far as my research none are offering this combination, this is supposed to be the first of its kind.]

#### Will you need specific information or advice?
[Yes, regarding billing(set standards) done in various industries across various regions, and a few more if this proposal gets accepted. ]

#### What are your goals and objectives?
[The goal is to standardize digital invoices by creating a centralized system, wherein the users can receive a digital cash memo for any legal purchase made.]

#### How will you evaluate project success?
[Expansion to various industries, userbase growth, and cashless transactions using thenewboston currency.]

#### What risks should you plan to manage?
[The risk management here would be just the opposite of success evaluation. Not being able to standardize or provide a trademark for digital billing and the possibility of generating fake invoices. ]

### Project milestones
The work has already begun and progressed to a certain extent. Below are the details of the remaining work.
Milestone 1:- Frontend design changes of the website and app (on or before Dec 10th).
Milestone 2:- Bugs fixing and testing(includes removal or addition of any value-adding feature, if found lucrative )(By Dec 30th).
Milestone 3:- Deployment(By Jan 15th).
Milestone 4:- Integration with thenewboston currency to provide cashless transaction and miscellaneous (As said, the idea is to launch an MVP and gain a decent user base and trust. In the meantime, thenewboston currency too would've gained traction, which would be just the right time to integrate the said currency and expand to other regions/industries as well. Hoping to accomplish this by the second or third quarter of the year 2021)

#### GitHub usernames, slack names, and roles of all team members:
- prajwalkulkarni |prajwalk.is18|Lead Developer

#### Additional information
I'm already working on the said idea and have made decent progress past few months. I'm working independently and it's getting tougher with the progression. Hence, I'm making this proposal primarily to find developers, designers to help me take this project further. If you found my idea insightful and willing to contribute, team up with me, please feel free to reach out to me.
LinkedIn - [Prajwal Kulkarni](https://www.linkedin.com/in/prajwal-kulkarni/)

**Comment by manishram** [comment]
Hey, @prajwalkulkarni please add your slack name as well so that we can contact you on slack.

**Comment by prajwalkulkarni** [comment]
Added slack username, please review. Thanks.

**Comment by manishram** [comment]
Hey, @prajwalkulkarni join thenewboston slack [here](https://join.slack.com/t/thenewboston/shared_invite/zt-j7j4ie92-ADy7GL3KAzCwSlaAVoDKLw). And also it seems like you have removed the milestones part from the proposal. Please add your project milestones. Once done, we are good to go.

**Comment by prajwalkulkarni** [comment]
Joined slack team and updated milestones. Please review.

**Comment by manishram** [comment]
Hey, @prajwalkulkarni your idea is impressive but can you please connect your idea with thenewboston digital currency in some way?
Some examples :
1. Charge thenewboston digital currency from merchants for using your invoice system.
2. You can also provide special offers for payments done with thenewboston digital currency.

**Comment by prajwalkulkarni** [comment]
Yes, I'm planning to integrate thenewboston currency in further stages, like you said offering special offers for payments done with thenewboston digital currency and also enable in-app payment to pay with thenewboston currency for fast and secure payments and other features which would make use of thenewboston currency, this would encourage customers to switch to using thenewboston currency over conventional payments like physical cash or other digital payments like Paypal. 
Reasons for implementation in further stages:
1) Initial target region is India where people aren't still confident about cryptocurrency or blockchain.
2) The currency doesn't hold any conversion value yet.
So, my Idea is to launch an MVP and gain a decent user base and trust. In the meantime, thenewbostoncurrency too would've gained traction, which would be just the right time to integrate the said currency and expand to other regions/industries as well. If I could get a team to work on this, we could make faster progress and eventually implement thenewboston currency.

**Comment by manishram** [comment]
@prajwalkulkarni please **add your points regarding connecting thenewboston** with your project in your **projectmilestones**. And update your answer for **How does it integrate with thenewboston digital currency work?**

After you are done with this, you need to comment down the repository URL of your project. You can provide a blank repository URL also if you have not started working on your project yet.

**Comment by prajwalkulkarni** [comment]
Updated. Please check. And, regarding repository there are 2, one for the merchant and other for the customer facing app, and both are private for obvious reasons. Which repository link am I supposed to share ?

**Comment by manishram** [comment]
You are supposed to share both repositories. But you know your project needs to be an open-source project right?
Rules and Guidelines: 
https://thenewboston.com/project-proposals/rules

**Comment by prajwalkulkarni** [comment]
I wasn't very well aware of that. Does the complete project supposed to be open-source, or, would be it alright, only if certain components are open-sourced?

**Comment by manishram** [comment]
Complete project needs to be an open-source project. The whole motive of this system is to support open-source projects.

**Comment by prajwalkulkarni** [comment]
Okay. Can I get 2-3days of time to think over it and proceed? Also, may I know, how long will these project proposals be open?

**Comment by manishram** [comment]
You can take your time. Your proposal will be closed after 30 days of no-activity.

**Comment by manishram** [comment]
I am not answering your question but here are few points:

1. Best part of open-source project is that you know the codes so you can always check if the organization is doing anything wrong. Also open-sourcing a project makes it available for everyone to use it for free. And user needs not to pay tons for money for it. Ex: Linux as an open-source os.
You can relate this with free tutorials on YouTube from thenewboston so that everyone can avail it for free.

2. Maintaining the same legacy thenewboston wants to support open-source projects.

Remember thenewboston is supporting open-source projects.

**Comment by manishram** [comment]
Regarding benefits for your project to be open-source, you will be eligible for receiving thenewboston digital currency as a funding from thenewboston which will be a support from us to your project.
