### ISSUE TITLE
Communications Branch

### ISSUE THREAD

**Issue by javina89** [thenewboston-developers/Project-Proposals#92]
**How would you describe your project?**
I would like to serve as a Chief Communications Officer for the various TNB teams. Communicating with each team to receive weekly updates identifying progress, opportunities, hardships, etc. will be my main responsibility. Through the intel I receive from these weekly meetings, I will develop status reports to inform our team and communities about the latest breakthroughs. Delivering qualitative data to our core team has the ability to improve our processes by streamlining our workflows.

Additionally, I would like to oversee the following teams:

Internal Communications Team – this team will collect and distribute data to the various teams. We can offer a monthly newsletter, intranet, etc.

External Communications Team – this team will collect and distribute data to the public. We can offer monthly newsletters, email marketing, social media marketing and advertising, blogs, podcasts, etc.

**What problem does it solve?**
The space of cryptocurrency is continuously evolving; therefore, so is TNB. This inevitably results in a fast-paced, ever-shifting environment. By maintaining an organized and optimized work space, we will minimize potential risks such as oversight issues, project management pitfalls, and the spread of misinformation. If our internal teams are organized and informed it will make communicating with external communities more effective; thus, expanding our scope as the company grows will be an easier process.

In addition to solving the problems listed above, this will be a great resource when making decisions through the treasury and budgeting board. Speculative voting is not enough to push TNB to implement trailblazing solutions. Voters who use our internal reports will have access to qualitative data, which paints a big-picture vision for this organization. 

**Who is the target market?**
We have two target markets for this project. The first target market is the internal team, consisting of everyone on payroll. The second target market is the external community, consisting of perspective investors, contributors, business partners and crypto-enthusiasts. 

**What do you think is the opportunity of this project?**
With how quickly this project is taking off, it is important to communicate status updates. The benefits of this project will boost morale throughout the organization, as well as generate buzz about our community. Optimizing our processes will enable TNB to surpass mainstream cryptocurrency.

**How does it integrate with thenewboston digital currency work?**
Having an established Communication team integrates with TNB’s mission to build the first instant, peer-to-peer, open-source payment network by making the team’s progress transparent, allowing us to make a bigger impact on the digital currency world at large.

**Will you need specific information or advice?**
Yes, I will need a designated member from each team to meet with to discuss updates on a weekly basis.

**What are your goals and objectives?**
The goals and objectives for this project are as follows:
1)	Receive weekly status updates from each team.
2)	Create an internal report. 
3)	Distribute the information collected using internal channels, i.e., intranet, newsletters, Slack/Discord, etc. via The Internal Communications team.
4)	Create an external report. 
5)	Distribute the information collected using external channel, i.e., social media, emails, blogs, podcasts, Slack/Discord, etc. via The External Communications team.
6)	Assess Key Performance Indicators (KPI) of communication implementation through evaluation methods.
7)	Adjust as necessary to improve Key Performance Indicators (KPI) of communication solutions.

**How will you evaluate project success?**
The success of this project will be assessed through various KPI measures. Utilizing a mixture of qualitative measures such as online reviews, surveys, focus groups, and interviews will identify valuable insights.

Measures such as turnover rates, new hire rate, employee engagement and internal communication reach provide quantitative data to support our efforts. Creating engaging resources to maintain a positive image will boost our reputation.

#### Tell us about your team members:
Full Name, Slack Username, GitHub Username, LinkedIn, Role, Account number

Jesus Avina, Chuy, javina89, https://www.linkedin.com/in/jesusavina/, Chief Communications Officer, f37aaaa15fe0cec8e7cf1809cc884610122c5d8886486b6c2492555229442a46

Taylor McNinch, Taylor M, tmcninch, https://www.linkedin.com/in/tmcninch/, Communications Director, 302ec39ca5be3167caa8fa1e7dd5488ee626837c2e6b5a87406d3deff07c42e4

#### List the roles of any additional team members you would be looking for?
We need to fill the following roles immediately: Internal Communications Manager, External Communications Manager

**Comment by buckyroberts** [comment]
Adding as team.
