### ISSUE TITLE
Patent Blockchain

### ISSUE THREAD

**Issue by Ishaan28malik** [thenewboston-developers/Project-Proposals#93]
#### How would you describe your project?
[ Block chain For Patents ]

#### What problem does it solve?
[ It 's a secured and fast method to provide security and assign Patents to individuals and organisations ]

#### Who is the target market?
[ All the Research students , startups , industries who want to get a Patent ]

#### What do you think is the opportunity of this project?
[ Great opportunity ]

#### How does it integrate with thenewboston digital currency work?
[ The patents that are being hosted and assigned will be charged for rent or ownership using TNB ]

#### Are there any competitors?
[ Not exactly ]

#### Will you need specific information or advice?
[ Yes ]

#### What are your goals and objectives?
[ To develop a full fledged app and chrome extension ]

#### How will you evaluate project success?
[ Once we are able to assign the patents approved for private and government organisations ]

#### What risks should you plan to manage?
[ The data privacy and cost of maintenance ]

#### What are your milestones?

- Milestone 1 : UX/UI ready - 21st Feb 2021
- Milestone 2 : Front-end ready - 10th March 2021

#### Tell us about your team members:

[ Ishaan Malik,Ishaan,Ishaan28malik,Fullstack Dev ]

#### List the roles of any additional team members you would be looking for?
[ No member ]

**Comment by manishram** [comment]
Hey @Ishaan28malik I liked you Project Proposal. Please provide the Project repository link. You can comment down here your empty project repo also.

**Comment by manishram** [comment]
I found Project Repo: https://github.com/Ishaan28malik/Patent-Blockchain
In the PR. Thanks
